apiVersion: iam.vultr.upbound.io/v1beta1
kind: OIDCIssuer
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/oidcissuer
  labels:
    testing.upbound.io/example-name: my_issuer
  name: my-issuer
spec:
  forProvider:
    name: external
