apiVersion: iam.vultr.upbound.io/v1beta1
kind: Organization
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/organization
  labels:
    testing.upbound.io/example-name: my_org
  name: my-org
spec:
  forProvider:
    name: my-org
    type: Personal/Team
