apiVersion: iam.vultr.upbound.io/v1beta1
kind: OrganizationRoleGroupAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/organizationrolegroupattachment
  labels:
    testing.upbound.io/example-name: role-group-attachment
  name: role-group-attachment
spec:
  forProvider:
    groupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    roleIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
