apiVersion: iam.vultr.upbound.io/v1beta1
kind: OrganizationGroup
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/organizationgroup
  labels:
    testing.upbound.io/example-name: my_group
  name: my-group
spec:
  forProvider:
    description: my group from terraform
    name: my-group
