apiVersion: iam.vultr.upbound.io/v1beta1
kind: OrganizationPolicyUserAttachment
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/organizationpolicyuserattachment
  labels:
    testing.upbound.io/example-name: policy-user-attachment
  name: policy-user-attachment
spec:
  forProvider:
    policyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    userIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
