apiVersion: compute.vultr.m.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/instance
  labels:
    testing.upbound.io/example-name: example-instance
  name: example-instance
  namespace: upbound-system
spec:
  forProvider:
    label: example-instance
    region: ewr
    plan: vc2-1c-1gb
    osId: 2136
    sshKeyIdsSelector:
      matchLabels:
        testing.upbound.io/example-name: example-instance
  writeConnectionSecretToRef:
    name: example-instance-conn

---

apiVersion: compute.vultr.m.upbound.io/v1beta1
kind: SSHKey
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/instance
  labels:
    testing.upbound.io/example-name: example-instance
  name: example-instance
  namespace: upbound-system
spec:
  forProvider:
    name: example-instance
    sshKey: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCyVGaw1PuEl98f4/7Kq3O9ZIvDw2OFOSXAFVqilSFNkHlefm1iMtPeqsIBp2t9cbGUf55xNDULz/bD/4BCV43yZ5lh0cUYuXALg9NI29ui7PEGReXjSpNwUD6ceN/78YOK41KAcecq+SS0bJ4b4amKZIJG3JWmDKljtv1dmSBCrTmEAQaOorxqGGBYmZS7NQumRe4lav5r6wOs8OACMANE1ejkeZsGFzJFNqvr5DuHdDL5FAudW23me3BDmrM9ifUzzjl1Jwku3bnRaCcjaxH8oTumt1a00mWci/1qUlaVFft085yvVq7KZbF2OPPbl+erDW91+EZ2FgEi+v1/CSJ5 example@uptest
