apiVersion: iam.vultr.m.upbound.io/v1beta1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/user
  labels:
    testing.upbound.io/example-name: my_user
  name: my-user
  namespace: upbound-system
spec:
  forProvider:
    apiEnabled: true
    email: user@vultr.com
    name: my user
    passwordSecretRef:
      key: example-key
      name: example-secret
