apiVersion: storage.vultr.upbound.io/v1beta1
kind: VirtualFileSystemStorage
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/virtualfilesystemstorage
  labels:
    testing.upbound.io/example-name: my_vfs_storage
  name: my-vfs-storage
spec:
  forProvider:
    label: vultr-vfs-storage
    region: ewr
    sizeGb: 10
    tags:
    - terraform
    - important
