// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type DNSDomainInitParameters struct {

	// The Domain's DNSSEC status. Valid options are enabled or disabled. Note disabled is default
	DNSSec *string `json:"dnsSec,omitempty" tf:"dns_sec,omitempty"`

	// Instance IP you want associated to domain. If omitted this will create a domain with no records.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`
}

type DNSDomainObservation struct {

	// The Domain's DNSSEC status. Valid options are enabled or disabled. Note disabled is default
	DNSSec *string `json:"dnsSec,omitempty" tf:"dns_sec,omitempty"`

	// The date the domain was added to your account.
	DateCreated *string `json:"dateCreated,omitempty" tf:"date_created,omitempty"`

	// The ID is the name of the domain.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Instance IP you want associated to domain. If omitted this will create a domain with no records.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`
}

type DNSDomainParameters struct {

	// The Domain's DNSSEC status. Valid options are enabled or disabled. Note disabled is default
	// +kubebuilder:validation:Optional
	DNSSec *string `json:"dnsSec,omitempty" tf:"dns_sec,omitempty"`

	// Instance IP you want associated to domain. If omitted this will create a domain with no records.
	// +kubebuilder:validation:Optional
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`
}

// DNSDomainSpec defines the desired state of DNSDomain
type DNSDomainSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   DNSDomainParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DNSDomainInitParameters `json:"initProvider,omitempty"`
}

// DNSDomainStatus defines the observed state of DNSDomain.
type DNSDomainStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               DNSDomainObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DNSDomain is the Schema for the DNSDomains API. Provides a Vultr DNS Domain resource. This can be used to create, read, modify, and delete DNS Domains.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vultr}
type DNSDomain struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              DNSDomainSpec   `json:"spec"`
	Status            DNSDomainStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DNSDomainList contains a list of DNSDomains
type DNSDomainList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DNSDomain `json:"items"`
}

// Repository type metadata.
var (
	DNSDomain_Kind             = "DNSDomain"
	DNSDomain_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DNSDomain_Kind}.String()
	DNSDomain_KindAPIVersion   = DNSDomain_Kind + "." + CRDGroupVersion.String()
	DNSDomain_GroupVersionKind = CRDGroupVersion.WithKind(DNSDomain_Kind)
)

func init() {
	SchemeBuilder.Register(&DNSDomain{}, &DNSDomainList{})
}
