// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type DNSRecordInitParameters struct {

	// IP Address of the instance the domain is associated with.
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// Name of the DNS Domain this record will belong to.
	// +crossplane:generate:reference:type=github.com/upbound/provider-vultr/apis/cluster/network/v1beta1.DNSDomain
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// Reference to a DNSDomain in network to populate domain.
	// +kubebuilder:validation:Optional
	DomainRef *v2.Reference `json:"domainRef,omitempty" tf:"-"`

	// Selector for a DNSDomain in network to populate domain.
	// +kubebuilder:validation:Optional
	DomainSelector *v2.Selector `json:"domainSelector,omitempty" tf:"-"`

	// Name (subdomain) for this record.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Priority of this record (only required for MX and SRV).
	Priority *int64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// The time to live of this record.
	TTL *int64 `json:"ttl,omitempty" tf:"ttl,omitempty"`

	// Type of record.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type DNSRecordObservation struct {

	// IP Address of the instance the domain is associated with.
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// Name of the DNS Domain this record will belong to.
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// ID associated with the record.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Name (subdomain) for this record.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Priority of this record (only required for MX and SRV).
	Priority *int64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// The time to live of this record.
	TTL *int64 `json:"ttl,omitempty" tf:"ttl,omitempty"`

	// Type of record.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type DNSRecordParameters struct {

	// IP Address of the instance the domain is associated with.
	// +kubebuilder:validation:Optional
	Data *string `json:"data,omitempty" tf:"data,omitempty"`

	// Name of the DNS Domain this record will belong to.
	// +crossplane:generate:reference:type=github.com/upbound/provider-vultr/apis/cluster/network/v1beta1.DNSDomain
	// +kubebuilder:validation:Optional
	Domain *string `json:"domain,omitempty" tf:"domain,omitempty"`

	// Reference to a DNSDomain in network to populate domain.
	// +kubebuilder:validation:Optional
	DomainRef *v2.Reference `json:"domainRef,omitempty" tf:"-"`

	// Selector for a DNSDomain in network to populate domain.
	// +kubebuilder:validation:Optional
	DomainSelector *v2.Selector `json:"domainSelector,omitempty" tf:"-"`

	// Name (subdomain) for this record.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Priority of this record (only required for MX and SRV).
	// +kubebuilder:validation:Optional
	Priority *int64 `json:"priority,omitempty" tf:"priority,omitempty"`

	// The time to live of this record.
	// +kubebuilder:validation:Optional
	TTL *int64 `json:"ttl,omitempty" tf:"ttl,omitempty"`

	// Type of record.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

// DNSRecordSpec defines the desired state of DNSRecord
type DNSRecordSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   DNSRecordParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DNSRecordInitParameters `json:"initProvider,omitempty"`
}

// DNSRecordStatus defines the observed state of DNSRecord.
type DNSRecordStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               DNSRecordObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// DNSRecord is the Schema for the DNSRecords API. Provides a Vultr DNS Record resource. This can be used to create, read, modify, and delete DNS Records.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vultr}
type DNSRecord struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.data) || (has(self.initProvider) && has(self.initProvider.data))",message="spec.forProvider.data is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   DNSRecordSpec   `json:"spec"`
	Status DNSRecordStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DNSRecordList contains a list of DNSRecords
type DNSRecordList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DNSRecord `json:"items"`
}

// Repository type metadata.
var (
	DNSRecord_Kind             = "DNSRecord"
	DNSRecord_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: DNSRecord_Kind}.String()
	DNSRecord_KindAPIVersion   = DNSRecord_Kind + "." + CRDGroupVersion.String()
	DNSRecord_GroupVersionKind = CRDGroupVersion.WithKind(DNSRecord_Kind)
)

func init() {
	SchemeBuilder.Register(&DNSRecord{}, &DNSRecordList{})
}
