// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type NATGatewayFirewallRuleInitParameters struct {

	// The NAT Gateway ID you want to attach this firewall rule to.
	// +crossplane:generate:reference:type=github.com/upbound/provider-vultr/apis/cluster/network/v1beta1.NATGateway
	NATGatewayID *string `json:"natGatewayId,omitempty" tf:"nat_gateway_id,omitempty"`

	// Reference to a NATGateway in network to populate natGatewayId.
	// +kubebuilder:validation:Optional
	NATGatewayIDRef *v2.Reference `json:"natGatewayIdRef,omitempty" tf:"-"`

	// Selector for a NATGateway in network to populate natGatewayId.
	// +kubebuilder:validation:Optional
	NATGatewayIDSelector *v2.Selector `json:"natGatewayIdSelector,omitempty" tf:"-"`

	// The notes for the new firewall rule.
	Notes *string `json:"notes,omitempty" tf:"notes,omitempty"`

	// The port or port range of the new firewall rule.
	Port *string `json:"port,omitempty" tf:"port,omitempty"`

	// The protocol of the new firewall rule (tcp, udp).
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// The subnet of the new firewall rule.
	Subnet *string `json:"subnet,omitempty" tf:"subnet,omitempty"`

	// The subnet size of the new firewall rule.
	SubnetSize *int64 `json:"subnetSize,omitempty" tf:"subnet_size,omitempty"`

	// The VPC ID associated with the NAT Gateway you want to attach this to.
	// +crossplane:generate:reference:type=github.com/upbound/provider-vultr/apis/cluster/network/v1beta1.VPC
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// Reference to a VPC in network to populate vpcId.
	// +kubebuilder:validation:Optional
	VPCIDRef *v2.Reference `json:"vpcIdRef,omitempty" tf:"-"`

	// Selector for a VPC in network to populate vpcId.
	// +kubebuilder:validation:Optional
	VPCIDSelector *v2.Selector `json:"vpcIdSelector,omitempty" tf:"-"`
}

type NATGatewayFirewallRuleObservation struct {

	// The action of the firewall rule (always accept).
	Action *string `json:"action,omitempty" tf:"action,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The NAT Gateway ID you want to attach this firewall rule to.
	NATGatewayID *string `json:"natGatewayId,omitempty" tf:"nat_gateway_id,omitempty"`

	// The notes for the new firewall rule.
	Notes *string `json:"notes,omitempty" tf:"notes,omitempty"`

	// The port or port range of the new firewall rule.
	Port *string `json:"port,omitempty" tf:"port,omitempty"`

	// The protocol of the new firewall rule (tcp, udp).
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// The subnet of the new firewall rule.
	Subnet *string `json:"subnet,omitempty" tf:"subnet,omitempty"`

	// The subnet size of the new firewall rule.
	SubnetSize *int64 `json:"subnetSize,omitempty" tf:"subnet_size,omitempty"`

	// The VPC ID associated with the NAT Gateway you want to attach this to.
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`
}

type NATGatewayFirewallRuleParameters struct {

	// The NAT Gateway ID you want to attach this firewall rule to.
	// +crossplane:generate:reference:type=github.com/upbound/provider-vultr/apis/cluster/network/v1beta1.NATGateway
	// +kubebuilder:validation:Optional
	NATGatewayID *string `json:"natGatewayId,omitempty" tf:"nat_gateway_id,omitempty"`

	// Reference to a NATGateway in network to populate natGatewayId.
	// +kubebuilder:validation:Optional
	NATGatewayIDRef *v2.Reference `json:"natGatewayIdRef,omitempty" tf:"-"`

	// Selector for a NATGateway in network to populate natGatewayId.
	// +kubebuilder:validation:Optional
	NATGatewayIDSelector *v2.Selector `json:"natGatewayIdSelector,omitempty" tf:"-"`

	// The notes for the new firewall rule.
	// +kubebuilder:validation:Optional
	Notes *string `json:"notes,omitempty" tf:"notes,omitempty"`

	// The port or port range of the new firewall rule.
	// +kubebuilder:validation:Optional
	Port *string `json:"port,omitempty" tf:"port,omitempty"`

	// The protocol of the new firewall rule (tcp, udp).
	// +kubebuilder:validation:Optional
	Protocol *string `json:"protocol,omitempty" tf:"protocol,omitempty"`

	// The subnet of the new firewall rule.
	// +kubebuilder:validation:Optional
	Subnet *string `json:"subnet,omitempty" tf:"subnet,omitempty"`

	// The subnet size of the new firewall rule.
	// +kubebuilder:validation:Optional
	SubnetSize *int64 `json:"subnetSize,omitempty" tf:"subnet_size,omitempty"`

	// The VPC ID associated with the NAT Gateway you want to attach this to.
	// +crossplane:generate:reference:type=github.com/upbound/provider-vultr/apis/cluster/network/v1beta1.VPC
	// +kubebuilder:validation:Optional
	VPCID *string `json:"vpcId,omitempty" tf:"vpc_id,omitempty"`

	// Reference to a VPC in network to populate vpcId.
	// +kubebuilder:validation:Optional
	VPCIDRef *v2.Reference `json:"vpcIdRef,omitempty" tf:"-"`

	// Selector for a VPC in network to populate vpcId.
	// +kubebuilder:validation:Optional
	VPCIDSelector *v2.Selector `json:"vpcIdSelector,omitempty" tf:"-"`
}

// NATGatewayFirewallRuleSpec defines the desired state of NATGatewayFirewallRule
type NATGatewayFirewallRuleSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   NATGatewayFirewallRuleParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider NATGatewayFirewallRuleInitParameters `json:"initProvider,omitempty"`
}

// NATGatewayFirewallRuleStatus defines the observed state of NATGatewayFirewallRule.
type NATGatewayFirewallRuleStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               NATGatewayFirewallRuleObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// NATGatewayFirewallRule is the Schema for the NATGatewayFirewallRules API. Provides a Vultr NAT Gateway firewall rule resource. This can be used to create, read, modify, and delete firewall rules for a NAT Gateway on your Vultr account.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vultr}
type NATGatewayFirewallRule struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.port) || (has(self.initProvider) && has(self.initProvider.port))",message="spec.forProvider.port is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.protocol) || (has(self.initProvider) && has(self.initProvider.protocol))",message="spec.forProvider.protocol is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.subnet) || (has(self.initProvider) && has(self.initProvider.subnet))",message="spec.forProvider.subnet is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.subnetSize) || (has(self.initProvider) && has(self.initProvider.subnetSize))",message="spec.forProvider.subnetSize is a required parameter"
	Spec   NATGatewayFirewallRuleSpec   `json:"spec"`
	Status NATGatewayFirewallRuleStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// NATGatewayFirewallRuleList contains a list of NATGatewayFirewallRules
type NATGatewayFirewallRuleList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []NATGatewayFirewallRule `json:"items"`
}

// Repository type metadata.
var (
	NATGatewayFirewallRule_Kind             = "NATGatewayFirewallRule"
	NATGatewayFirewallRule_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: NATGatewayFirewallRule_Kind}.String()
	NATGatewayFirewallRule_KindAPIVersion   = NATGatewayFirewallRule_Kind + "." + CRDGroupVersion.String()
	NATGatewayFirewallRule_GroupVersionKind = CRDGroupVersion.WithKind(NATGatewayFirewallRule_Kind)
)

func init() {
	SchemeBuilder.Register(&NATGatewayFirewallRule{}, &NATGatewayFirewallRuleList{})
}
