//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupsScheduleInitParameters) DeepCopyInto(out *BackupsScheduleInitParameters) {
	*out = *in
	if in.Dom != nil {
		in, out := &in.Dom, &out.Dom
		*out = new(int64)
		**out = **in
	}
	if in.Dow != nil {
		in, out := &in.Dow, &out.Dow
		*out = new(int64)
		**out = **in
	}
	if in.Hour != nil {
		in, out := &in.Hour, &out.Hour
		*out = new(int64)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupsScheduleInitParameters.
func (in *BackupsScheduleInitParameters) DeepCopy() *BackupsScheduleInitParameters {
	if in == nil {
		return nil
	}
	out := new(BackupsScheduleInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupsScheduleObservation) DeepCopyInto(out *BackupsScheduleObservation) {
	*out = *in
	if in.Dom != nil {
		in, out := &in.Dom, &out.Dom
		*out = new(int64)
		**out = **in
	}
	if in.Dow != nil {
		in, out := &in.Dow, &out.Dow
		*out = new(int64)
		**out = **in
	}
	if in.Hour != nil {
		in, out := &in.Hour, &out.Hour
		*out = new(int64)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupsScheduleObservation.
func (in *BackupsScheduleObservation) DeepCopy() *BackupsScheduleObservation {
	if in == nil {
		return nil
	}
	out := new(BackupsScheduleObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BackupsScheduleParameters) DeepCopyInto(out *BackupsScheduleParameters) {
	*out = *in
	if in.Dom != nil {
		in, out := &in.Dom, &out.Dom
		*out = new(int64)
		**out = **in
	}
	if in.Dow != nil {
		in, out := &in.Dow, &out.Dow
		*out = new(int64)
		**out = **in
	}
	if in.Hour != nil {
		in, out := &in.Hour, &out.Hour
		*out = new(int64)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BackupsScheduleParameters.
func (in *BackupsScheduleParameters) DeepCopy() *BackupsScheduleParameters {
	if in == nil {
		return nil
	}
	out := new(BackupsScheduleParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BareMetalServer) DeepCopyInto(out *BareMetalServer) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BareMetalServer.
func (in *BareMetalServer) DeepCopy() *BareMetalServer {
	if in == nil {
		return nil
	}
	out := new(BareMetalServer)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BareMetalServer) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BareMetalServerInitParameters) DeepCopyInto(out *BareMetalServerInitParameters) {
	*out = *in
	if in.ActivationEmail != nil {
		in, out := &in.ActivationEmail, &out.ActivationEmail
		*out = new(bool)
		**out = **in
	}
	if in.AppID != nil {
		in, out := &in.AppID, &out.AppID
		*out = new(int64)
		**out = **in
	}
	if in.AppVariables != nil {
		in, out := &in.AppVariables, &out.AppVariables
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.EnableIPv6 != nil {
		in, out := &in.EnableIPv6, &out.EnableIPv6
		*out = new(bool)
		**out = **in
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.ImageID != nil {
		in, out := &in.ImageID, &out.ImageID
		*out = new(string)
		**out = **in
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
	if in.MdiskMode != nil {
		in, out := &in.MdiskMode, &out.MdiskMode
		*out = new(string)
		**out = **in
	}
	if in.OsID != nil {
		in, out := &in.OsID, &out.OsID
		*out = new(int64)
		**out = **in
	}
	if in.PersistentPxe != nil {
		in, out := &in.PersistentPxe, &out.PersistentPxe
		*out = new(bool)
		**out = **in
	}
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ReservedIPv4 != nil {
		in, out := &in.ReservedIPv4, &out.ReservedIPv4
		*out = new(string)
		**out = **in
	}
	if in.SSHKeyIds != nil {
		in, out := &in.SSHKeyIds, &out.SSHKeyIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SSHKeyIdsRefs != nil {
		in, out := &in.SSHKeyIdsRefs, &out.SSHKeyIdsRefs
		*out = make([]v2.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SSHKeyIdsSelector != nil {
		in, out := &in.SSHKeyIdsSelector, &out.SSHKeyIdsSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ScriptID != nil {
		in, out := &in.ScriptID, &out.ScriptID
		*out = new(string)
		**out = **in
	}
	if in.ScriptIDRef != nil {
		in, out := &in.ScriptIDRef, &out.ScriptIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ScriptIDSelector != nil {
		in, out := &in.ScriptIDSelector, &out.ScriptIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.SnapshotID != nil {
		in, out := &in.SnapshotID, &out.SnapshotID
		*out = new(string)
		**out = **in
	}
	if in.SnapshotIDRef != nil {
		in, out := &in.SnapshotIDRef, &out.SnapshotIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.SnapshotIDSelector != nil {
		in, out := &in.SnapshotIDSelector, &out.SnapshotIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UserData != nil {
		in, out := &in.UserData, &out.UserData
		*out = new(string)
		**out = **in
	}
	if in.UserScheme != nil {
		in, out := &in.UserScheme, &out.UserScheme
		*out = new(string)
		**out = **in
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
	if in.VPCIDRef != nil {
		in, out := &in.VPCIDRef, &out.VPCIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.VPCIDSelector != nil {
		in, out := &in.VPCIDSelector, &out.VPCIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Vpc2Ids != nil {
		in, out := &in.Vpc2Ids, &out.Vpc2Ids
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BareMetalServerInitParameters.
func (in *BareMetalServerInitParameters) DeepCopy() *BareMetalServerInitParameters {
	if in == nil {
		return nil
	}
	out := new(BareMetalServerInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BareMetalServerList) DeepCopyInto(out *BareMetalServerList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]BareMetalServer, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BareMetalServerList.
func (in *BareMetalServerList) DeepCopy() *BareMetalServerList {
	if in == nil {
		return nil
	}
	out := new(BareMetalServerList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *BareMetalServerList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BareMetalServerObservation) DeepCopyInto(out *BareMetalServerObservation) {
	*out = *in
	if in.ActivationEmail != nil {
		in, out := &in.ActivationEmail, &out.ActivationEmail
		*out = new(bool)
		**out = **in
	}
	if in.AppID != nil {
		in, out := &in.AppID, &out.AppID
		*out = new(int64)
		**out = **in
	}
	if in.AppVariables != nil {
		in, out := &in.AppVariables, &out.AppVariables
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.CPUCount != nil {
		in, out := &in.CPUCount, &out.CPUCount
		*out = new(int64)
		**out = **in
	}
	if in.DateCreated != nil {
		in, out := &in.DateCreated, &out.DateCreated
		*out = new(string)
		**out = **in
	}
	if in.Disk != nil {
		in, out := &in.Disk, &out.Disk
		*out = new(string)
		**out = **in
	}
	if in.EnableIPv6 != nil {
		in, out := &in.EnableIPv6, &out.EnableIPv6
		*out = new(bool)
		**out = **in
	}
	if in.GatewayV4 != nil {
		in, out := &in.GatewayV4, &out.GatewayV4
		*out = new(string)
		**out = **in
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ImageID != nil {
		in, out := &in.ImageID, &out.ImageID
		*out = new(string)
		**out = **in
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
	if in.MacAddress != nil {
		in, out := &in.MacAddress, &out.MacAddress
		*out = new(int64)
		**out = **in
	}
	if in.MainIP != nil {
		in, out := &in.MainIP, &out.MainIP
		*out = new(string)
		**out = **in
	}
	if in.MdiskMode != nil {
		in, out := &in.MdiskMode, &out.MdiskMode
		*out = new(string)
		**out = **in
	}
	if in.NetmaskV4 != nil {
		in, out := &in.NetmaskV4, &out.NetmaskV4
		*out = new(string)
		**out = **in
	}
	if in.Os != nil {
		in, out := &in.Os, &out.Os
		*out = new(string)
		**out = **in
	}
	if in.OsID != nil {
		in, out := &in.OsID, &out.OsID
		*out = new(int64)
		**out = **in
	}
	if in.PersistentPxe != nil {
		in, out := &in.PersistentPxe, &out.PersistentPxe
		*out = new(bool)
		**out = **in
	}
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(string)
		**out = **in
	}
	if in.RAM != nil {
		in, out := &in.RAM, &out.RAM
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ReservedIPv4 != nil {
		in, out := &in.ReservedIPv4, &out.ReservedIPv4
		*out = new(string)
		**out = **in
	}
	if in.SSHKeyIds != nil {
		in, out := &in.SSHKeyIds, &out.SSHKeyIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ScriptID != nil {
		in, out := &in.ScriptID, &out.ScriptID
		*out = new(string)
		**out = **in
	}
	if in.SnapshotID != nil {
		in, out := &in.SnapshotID, &out.SnapshotID
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UserData != nil {
		in, out := &in.UserData, &out.UserData
		*out = new(string)
		**out = **in
	}
	if in.UserScheme != nil {
		in, out := &in.UserScheme, &out.UserScheme
		*out = new(string)
		**out = **in
	}
	if in.V6MainIP != nil {
		in, out := &in.V6MainIP, &out.V6MainIP
		*out = new(string)
		**out = **in
	}
	if in.V6Network != nil {
		in, out := &in.V6Network, &out.V6Network
		*out = new(string)
		**out = **in
	}
	if in.V6NetworkSize != nil {
		in, out := &in.V6NetworkSize, &out.V6NetworkSize
		*out = new(int64)
		**out = **in
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
	if in.Vpc2Ids != nil {
		in, out := &in.Vpc2Ids, &out.Vpc2Ids
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BareMetalServerObservation.
func (in *BareMetalServerObservation) DeepCopy() *BareMetalServerObservation {
	if in == nil {
		return nil
	}
	out := new(BareMetalServerObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BareMetalServerParameters) DeepCopyInto(out *BareMetalServerParameters) {
	*out = *in
	if in.ActivationEmail != nil {
		in, out := &in.ActivationEmail, &out.ActivationEmail
		*out = new(bool)
		**out = **in
	}
	if in.AppID != nil {
		in, out := &in.AppID, &out.AppID
		*out = new(int64)
		**out = **in
	}
	if in.AppVariables != nil {
		in, out := &in.AppVariables, &out.AppVariables
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.EnableIPv6 != nil {
		in, out := &in.EnableIPv6, &out.EnableIPv6
		*out = new(bool)
		**out = **in
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.ImageID != nil {
		in, out := &in.ImageID, &out.ImageID
		*out = new(string)
		**out = **in
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
	if in.MdiskMode != nil {
		in, out := &in.MdiskMode, &out.MdiskMode
		*out = new(string)
		**out = **in
	}
	if in.OsID != nil {
		in, out := &in.OsID, &out.OsID
		*out = new(int64)
		**out = **in
	}
	if in.PersistentPxe != nil {
		in, out := &in.PersistentPxe, &out.PersistentPxe
		*out = new(bool)
		**out = **in
	}
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ReservedIPv4 != nil {
		in, out := &in.ReservedIPv4, &out.ReservedIPv4
		*out = new(string)
		**out = **in
	}
	if in.SSHKeyIds != nil {
		in, out := &in.SSHKeyIds, &out.SSHKeyIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SSHKeyIdsRefs != nil {
		in, out := &in.SSHKeyIdsRefs, &out.SSHKeyIdsRefs
		*out = make([]v2.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SSHKeyIdsSelector != nil {
		in, out := &in.SSHKeyIdsSelector, &out.SSHKeyIdsSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ScriptID != nil {
		in, out := &in.ScriptID, &out.ScriptID
		*out = new(string)
		**out = **in
	}
	if in.ScriptIDRef != nil {
		in, out := &in.ScriptIDRef, &out.ScriptIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ScriptIDSelector != nil {
		in, out := &in.ScriptIDSelector, &out.ScriptIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.SnapshotID != nil {
		in, out := &in.SnapshotID, &out.SnapshotID
		*out = new(string)
		**out = **in
	}
	if in.SnapshotIDRef != nil {
		in, out := &in.SnapshotIDRef, &out.SnapshotIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.SnapshotIDSelector != nil {
		in, out := &in.SnapshotIDSelector, &out.SnapshotIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UserData != nil {
		in, out := &in.UserData, &out.UserData
		*out = new(string)
		**out = **in
	}
	if in.UserScheme != nil {
		in, out := &in.UserScheme, &out.UserScheme
		*out = new(string)
		**out = **in
	}
	if in.VPCID != nil {
		in, out := &in.VPCID, &out.VPCID
		*out = new(string)
		**out = **in
	}
	if in.VPCIDRef != nil {
		in, out := &in.VPCIDRef, &out.VPCIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.VPCIDSelector != nil {
		in, out := &in.VPCIDSelector, &out.VPCIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Vpc2Ids != nil {
		in, out := &in.Vpc2Ids, &out.Vpc2Ids
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BareMetalServerParameters.
func (in *BareMetalServerParameters) DeepCopy() *BareMetalServerParameters {
	if in == nil {
		return nil
	}
	out := new(BareMetalServerParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BareMetalServerSpec) DeepCopyInto(out *BareMetalServerSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BareMetalServerSpec.
func (in *BareMetalServerSpec) DeepCopy() *BareMetalServerSpec {
	if in == nil {
		return nil
	}
	out := new(BareMetalServerSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BareMetalServerStatus) DeepCopyInto(out *BareMetalServerStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BareMetalServerStatus.
func (in *BareMetalServerStatus) DeepCopy() *BareMetalServerStatus {
	if in == nil {
		return nil
	}
	out := new(BareMetalServerStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockDevicesInitParameters) DeepCopyInto(out *BlockDevicesInitParameters) {
	*out = *in
	if in.BlockID != nil {
		in, out := &in.BlockID, &out.BlockID
		*out = new(string)
		**out = **in
	}
	if in.Bootable != nil {
		in, out := &in.Bootable, &out.Bootable
		*out = new(bool)
		**out = **in
	}
	if in.DiskSize != nil {
		in, out := &in.DiskSize, &out.DiskSize
		*out = new(int64)
		**out = **in
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockDevicesInitParameters.
func (in *BlockDevicesInitParameters) DeepCopy() *BlockDevicesInitParameters {
	if in == nil {
		return nil
	}
	out := new(BlockDevicesInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockDevicesObservation) DeepCopyInto(out *BlockDevicesObservation) {
	*out = *in
	if in.BlockID != nil {
		in, out := &in.BlockID, &out.BlockID
		*out = new(string)
		**out = **in
	}
	if in.Bootable != nil {
		in, out := &in.Bootable, &out.Bootable
		*out = new(bool)
		**out = **in
	}
	if in.DiskSize != nil {
		in, out := &in.DiskSize, &out.DiskSize
		*out = new(int64)
		**out = **in
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockDevicesObservation.
func (in *BlockDevicesObservation) DeepCopy() *BlockDevicesObservation {
	if in == nil {
		return nil
	}
	out := new(BlockDevicesObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *BlockDevicesParameters) DeepCopyInto(out *BlockDevicesParameters) {
	*out = *in
	if in.BlockID != nil {
		in, out := &in.BlockID, &out.BlockID
		*out = new(string)
		**out = **in
	}
	if in.Bootable != nil {
		in, out := &in.Bootable, &out.Bootable
		*out = new(bool)
		**out = **in
	}
	if in.DiskSize != nil {
		in, out := &in.DiskSize, &out.DiskSize
		*out = new(int64)
		**out = **in
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new BlockDevicesParameters.
func (in *BlockDevicesParameters) DeepCopy() *BlockDevicesParameters {
	if in == nil {
		return nil
	}
	out := new(BlockDevicesParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISOPrivate) DeepCopyInto(out *ISOPrivate) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISOPrivate.
func (in *ISOPrivate) DeepCopy() *ISOPrivate {
	if in == nil {
		return nil
	}
	out := new(ISOPrivate)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ISOPrivate) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISOPrivateInitParameters) DeepCopyInto(out *ISOPrivateInitParameters) {
	*out = *in
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISOPrivateInitParameters.
func (in *ISOPrivateInitParameters) DeepCopy() *ISOPrivateInitParameters {
	if in == nil {
		return nil
	}
	out := new(ISOPrivateInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISOPrivateList) DeepCopyInto(out *ISOPrivateList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ISOPrivate, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISOPrivateList.
func (in *ISOPrivateList) DeepCopy() *ISOPrivateList {
	if in == nil {
		return nil
	}
	out := new(ISOPrivateList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ISOPrivateList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISOPrivateObservation) DeepCopyInto(out *ISOPrivateObservation) {
	*out = *in
	if in.DateCreated != nil {
		in, out := &in.DateCreated, &out.DateCreated
		*out = new(string)
		**out = **in
	}
	if in.Filename != nil {
		in, out := &in.Filename, &out.Filename
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Md5Sum != nil {
		in, out := &in.Md5Sum, &out.Md5Sum
		*out = new(string)
		**out = **in
	}
	if in.Sha512Sum != nil {
		in, out := &in.Sha512Sum, &out.Sha512Sum
		*out = new(string)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(int64)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISOPrivateObservation.
func (in *ISOPrivateObservation) DeepCopy() *ISOPrivateObservation {
	if in == nil {
		return nil
	}
	out := new(ISOPrivateObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISOPrivateParameters) DeepCopyInto(out *ISOPrivateParameters) {
	*out = *in
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISOPrivateParameters.
func (in *ISOPrivateParameters) DeepCopy() *ISOPrivateParameters {
	if in == nil {
		return nil
	}
	out := new(ISOPrivateParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISOPrivateSpec) DeepCopyInto(out *ISOPrivateSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISOPrivateSpec.
func (in *ISOPrivateSpec) DeepCopy() *ISOPrivateSpec {
	if in == nil {
		return nil
	}
	out := new(ISOPrivateSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ISOPrivateStatus) DeepCopyInto(out *ISOPrivateStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ISOPrivateStatus.
func (in *ISOPrivateStatus) DeepCopy() *ISOPrivateStatus {
	if in == nil {
		return nil
	}
	out := new(ISOPrivateStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Inference) DeepCopyInto(out *Inference) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Inference.
func (in *Inference) DeepCopy() *Inference {
	if in == nil {
		return nil
	}
	out := new(Inference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Inference) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceInitParameters) DeepCopyInto(out *InferenceInitParameters) {
	*out = *in
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceInitParameters.
func (in *InferenceInitParameters) DeepCopy() *InferenceInitParameters {
	if in == nil {
		return nil
	}
	out := new(InferenceInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceList) DeepCopyInto(out *InferenceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Inference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceList.
func (in *InferenceList) DeepCopy() *InferenceList {
	if in == nil {
		return nil
	}
	out := new(InferenceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InferenceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceObservation) DeepCopyInto(out *InferenceObservation) {
	*out = *in
	if in.DateCreated != nil {
		in, out := &in.DateCreated, &out.DateCreated
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceObservation.
func (in *InferenceObservation) DeepCopy() *InferenceObservation {
	if in == nil {
		return nil
	}
	out := new(InferenceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceParameters) DeepCopyInto(out *InferenceParameters) {
	*out = *in
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceParameters.
func (in *InferenceParameters) DeepCopy() *InferenceParameters {
	if in == nil {
		return nil
	}
	out := new(InferenceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceSpec) DeepCopyInto(out *InferenceSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceSpec.
func (in *InferenceSpec) DeepCopy() *InferenceSpec {
	if in == nil {
		return nil
	}
	out := new(InferenceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InferenceStatus) DeepCopyInto(out *InferenceStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InferenceStatus.
func (in *InferenceStatus) DeepCopy() *InferenceStatus {
	if in == nil {
		return nil
	}
	out := new(InferenceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Instance) DeepCopyInto(out *Instance) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Instance.
func (in *Instance) DeepCopy() *Instance {
	if in == nil {
		return nil
	}
	out := new(Instance)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Instance) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceIPv4) DeepCopyInto(out *InstanceIPv4) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceIPv4.
func (in *InstanceIPv4) DeepCopy() *InstanceIPv4 {
	if in == nil {
		return nil
	}
	out := new(InstanceIPv4)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstanceIPv4) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceIPv4InitParameters) DeepCopyInto(out *InstanceIPv4InitParameters) {
	*out = *in
	if in.InstanceID != nil {
		in, out := &in.InstanceID, &out.InstanceID
		*out = new(string)
		**out = **in
	}
	if in.InstanceIDRef != nil {
		in, out := &in.InstanceIDRef, &out.InstanceIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.InstanceIDSelector != nil {
		in, out := &in.InstanceIDSelector, &out.InstanceIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Reboot != nil {
		in, out := &in.Reboot, &out.Reboot
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceIPv4InitParameters.
func (in *InstanceIPv4InitParameters) DeepCopy() *InstanceIPv4InitParameters {
	if in == nil {
		return nil
	}
	out := new(InstanceIPv4InitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceIPv4List) DeepCopyInto(out *InstanceIPv4List) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]InstanceIPv4, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceIPv4List.
func (in *InstanceIPv4List) DeepCopy() *InstanceIPv4List {
	if in == nil {
		return nil
	}
	out := new(InstanceIPv4List)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstanceIPv4List) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceIPv4Observation) DeepCopyInto(out *InstanceIPv4Observation) {
	*out = *in
	if in.Gateway != nil {
		in, out := &in.Gateway, &out.Gateway
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.IP != nil {
		in, out := &in.IP, &out.IP
		*out = new(string)
		**out = **in
	}
	if in.InstanceID != nil {
		in, out := &in.InstanceID, &out.InstanceID
		*out = new(string)
		**out = **in
	}
	if in.Netmask != nil {
		in, out := &in.Netmask, &out.Netmask
		*out = new(string)
		**out = **in
	}
	if in.Reboot != nil {
		in, out := &in.Reboot, &out.Reboot
		*out = new(bool)
		**out = **in
	}
	if in.Reverse != nil {
		in, out := &in.Reverse, &out.Reverse
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceIPv4Observation.
func (in *InstanceIPv4Observation) DeepCopy() *InstanceIPv4Observation {
	if in == nil {
		return nil
	}
	out := new(InstanceIPv4Observation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceIPv4Parameters) DeepCopyInto(out *InstanceIPv4Parameters) {
	*out = *in
	if in.InstanceID != nil {
		in, out := &in.InstanceID, &out.InstanceID
		*out = new(string)
		**out = **in
	}
	if in.InstanceIDRef != nil {
		in, out := &in.InstanceIDRef, &out.InstanceIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.InstanceIDSelector != nil {
		in, out := &in.InstanceIDSelector, &out.InstanceIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Reboot != nil {
		in, out := &in.Reboot, &out.Reboot
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceIPv4Parameters.
func (in *InstanceIPv4Parameters) DeepCopy() *InstanceIPv4Parameters {
	if in == nil {
		return nil
	}
	out := new(InstanceIPv4Parameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceIPv4Spec) DeepCopyInto(out *InstanceIPv4Spec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceIPv4Spec.
func (in *InstanceIPv4Spec) DeepCopy() *InstanceIPv4Spec {
	if in == nil {
		return nil
	}
	out := new(InstanceIPv4Spec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceIPv4Status) DeepCopyInto(out *InstanceIPv4Status) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceIPv4Status.
func (in *InstanceIPv4Status) DeepCopy() *InstanceIPv4Status {
	if in == nil {
		return nil
	}
	out := new(InstanceIPv4Status)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceInitParameters) DeepCopyInto(out *InstanceInitParameters) {
	*out = *in
	if in.ActivationEmail != nil {
		in, out := &in.ActivationEmail, &out.ActivationEmail
		*out = new(bool)
		**out = **in
	}
	if in.AppID != nil {
		in, out := &in.AppID, &out.AppID
		*out = new(int64)
		**out = **in
	}
	if in.AppVariables != nil {
		in, out := &in.AppVariables, &out.AppVariables
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Backups != nil {
		in, out := &in.Backups, &out.Backups
		*out = new(string)
		**out = **in
	}
	if in.BackupsSchedule != nil {
		in, out := &in.BackupsSchedule, &out.BackupsSchedule
		*out = new(BackupsScheduleInitParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.BlockDevices != nil {
		in, out := &in.BlockDevices, &out.BlockDevices
		*out = make([]BlockDevicesInitParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DdosProtection != nil {
		in, out := &in.DdosProtection, &out.DdosProtection
		*out = new(bool)
		**out = **in
	}
	if in.DisablePublicIPv4 != nil {
		in, out := &in.DisablePublicIPv4, &out.DisablePublicIPv4
		*out = new(bool)
		**out = **in
	}
	if in.EnableIPv6 != nil {
		in, out := &in.EnableIPv6, &out.EnableIPv6
		*out = new(bool)
		**out = **in
	}
	if in.FirewallGroupID != nil {
		in, out := &in.FirewallGroupID, &out.FirewallGroupID
		*out = new(string)
		**out = **in
	}
	if in.FirewallGroupIDRef != nil {
		in, out := &in.FirewallGroupIDRef, &out.FirewallGroupIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.FirewallGroupIDSelector != nil {
		in, out := &in.FirewallGroupIDSelector, &out.FirewallGroupIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.ImageID != nil {
		in, out := &in.ImageID, &out.ImageID
		*out = new(string)
		**out = **in
	}
	if in.IpxeChainURL != nil {
		in, out := &in.IpxeChainURL, &out.IpxeChainURL
		*out = new(string)
		**out = **in
	}
	if in.IsoID != nil {
		in, out := &in.IsoID, &out.IsoID
		*out = new(string)
		**out = **in
	}
	if in.IsoIDRef != nil {
		in, out := &in.IsoIDRef, &out.IsoIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.IsoIDSelector != nil {
		in, out := &in.IsoIDSelector, &out.IsoIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
	if in.OsID != nil {
		in, out := &in.OsID, &out.OsID
		*out = new(int64)
		**out = **in
	}
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ReservedIPID != nil {
		in, out := &in.ReservedIPID, &out.ReservedIPID
		*out = new(string)
		**out = **in
	}
	if in.ReservedIPIDRef != nil {
		in, out := &in.ReservedIPIDRef, &out.ReservedIPIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ReservedIPIDSelector != nil {
		in, out := &in.ReservedIPIDSelector, &out.ReservedIPIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.SSHKeyIds != nil {
		in, out := &in.SSHKeyIds, &out.SSHKeyIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SSHKeyIdsRefs != nil {
		in, out := &in.SSHKeyIdsRefs, &out.SSHKeyIdsRefs
		*out = make([]v2.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SSHKeyIdsSelector != nil {
		in, out := &in.SSHKeyIdsSelector, &out.SSHKeyIdsSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ScriptID != nil {
		in, out := &in.ScriptID, &out.ScriptID
		*out = new(string)
		**out = **in
	}
	if in.ScriptIDRef != nil {
		in, out := &in.ScriptIDRef, &out.ScriptIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ScriptIDSelector != nil {
		in, out := &in.ScriptIDSelector, &out.ScriptIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.SnapshotID != nil {
		in, out := &in.SnapshotID, &out.SnapshotID
		*out = new(string)
		**out = **in
	}
	if in.SnapshotIDRef != nil {
		in, out := &in.SnapshotIDRef, &out.SnapshotIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.SnapshotIDSelector != nil {
		in, out := &in.SnapshotIDSelector, &out.SnapshotIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UserData != nil {
		in, out := &in.UserData, &out.UserData
		*out = new(string)
		**out = **in
	}
	if in.UserScheme != nil {
		in, out := &in.UserScheme, &out.UserScheme
		*out = new(string)
		**out = **in
	}
	if in.VPCIds != nil {
		in, out := &in.VPCIds, &out.VPCIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.VPCIdsRefs != nil {
		in, out := &in.VPCIdsRefs, &out.VPCIdsRefs
		*out = make([]v2.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VPCIdsSelector != nil {
		in, out := &in.VPCIdsSelector, &out.VPCIdsSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.VPCOnly != nil {
		in, out := &in.VPCOnly, &out.VPCOnly
		*out = new(bool)
		**out = **in
	}
	if in.Vpc2Ids != nil {
		in, out := &in.Vpc2Ids, &out.Vpc2Ids
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceInitParameters.
func (in *InstanceInitParameters) DeepCopy() *InstanceInitParameters {
	if in == nil {
		return nil
	}
	out := new(InstanceInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceList) DeepCopyInto(out *InstanceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Instance, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceList.
func (in *InstanceList) DeepCopy() *InstanceList {
	if in == nil {
		return nil
	}
	out := new(InstanceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *InstanceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceObservation) DeepCopyInto(out *InstanceObservation) {
	*out = *in
	if in.ActivationEmail != nil {
		in, out := &in.ActivationEmail, &out.ActivationEmail
		*out = new(bool)
		**out = **in
	}
	if in.AllowedBandwidth != nil {
		in, out := &in.AllowedBandwidth, &out.AllowedBandwidth
		*out = new(int64)
		**out = **in
	}
	if in.AppID != nil {
		in, out := &in.AppID, &out.AppID
		*out = new(int64)
		**out = **in
	}
	if in.AppVariables != nil {
		in, out := &in.AppVariables, &out.AppVariables
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Backups != nil {
		in, out := &in.Backups, &out.Backups
		*out = new(string)
		**out = **in
	}
	if in.BackupsSchedule != nil {
		in, out := &in.BackupsSchedule, &out.BackupsSchedule
		*out = new(BackupsScheduleObservation)
		(*in).DeepCopyInto(*out)
	}
	if in.BlockDevices != nil {
		in, out := &in.BlockDevices, &out.BlockDevices
		*out = make([]BlockDevicesObservation, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DateCreated != nil {
		in, out := &in.DateCreated, &out.DateCreated
		*out = new(string)
		**out = **in
	}
	if in.DdosProtection != nil {
		in, out := &in.DdosProtection, &out.DdosProtection
		*out = new(bool)
		**out = **in
	}
	if in.DisablePublicIPv4 != nil {
		in, out := &in.DisablePublicIPv4, &out.DisablePublicIPv4
		*out = new(bool)
		**out = **in
	}
	if in.Disk != nil {
		in, out := &in.Disk, &out.Disk
		*out = new(int64)
		**out = **in
	}
	if in.EnableIPv6 != nil {
		in, out := &in.EnableIPv6, &out.EnableIPv6
		*out = new(bool)
		**out = **in
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.FirewallGroupID != nil {
		in, out := &in.FirewallGroupID, &out.FirewallGroupID
		*out = new(string)
		**out = **in
	}
	if in.GatewayV4 != nil {
		in, out := &in.GatewayV4, &out.GatewayV4
		*out = new(string)
		**out = **in
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.ImageID != nil {
		in, out := &in.ImageID, &out.ImageID
		*out = new(string)
		**out = **in
	}
	if in.InternalIP != nil {
		in, out := &in.InternalIP, &out.InternalIP
		*out = new(string)
		**out = **in
	}
	if in.IpxeChainURL != nil {
		in, out := &in.IpxeChainURL, &out.IpxeChainURL
		*out = new(string)
		**out = **in
	}
	if in.IsoID != nil {
		in, out := &in.IsoID, &out.IsoID
		*out = new(string)
		**out = **in
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
	if in.MainIP != nil {
		in, out := &in.MainIP, &out.MainIP
		*out = new(string)
		**out = **in
	}
	if in.NetmaskV4 != nil {
		in, out := &in.NetmaskV4, &out.NetmaskV4
		*out = new(string)
		**out = **in
	}
	if in.Os != nil {
		in, out := &in.Os, &out.Os
		*out = new(string)
		**out = **in
	}
	if in.OsID != nil {
		in, out := &in.OsID, &out.OsID
		*out = new(int64)
		**out = **in
	}
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(string)
		**out = **in
	}
	if in.PowerStatus != nil {
		in, out := &in.PowerStatus, &out.PowerStatus
		*out = new(string)
		**out = **in
	}
	if in.RAM != nil {
		in, out := &in.RAM, &out.RAM
		*out = new(int64)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ReservedIPID != nil {
		in, out := &in.ReservedIPID, &out.ReservedIPID
		*out = new(string)
		**out = **in
	}
	if in.SSHKeyIds != nil {
		in, out := &in.SSHKeyIds, &out.SSHKeyIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.ScriptID != nil {
		in, out := &in.ScriptID, &out.ScriptID
		*out = new(string)
		**out = **in
	}
	if in.ServerStatus != nil {
		in, out := &in.ServerStatus, &out.ServerStatus
		*out = new(string)
		**out = **in
	}
	if in.SnapshotID != nil {
		in, out := &in.SnapshotID, &out.SnapshotID
		*out = new(string)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UserData != nil {
		in, out := &in.UserData, &out.UserData
		*out = new(string)
		**out = **in
	}
	if in.UserScheme != nil {
		in, out := &in.UserScheme, &out.UserScheme
		*out = new(string)
		**out = **in
	}
	if in.V6MainIP != nil {
		in, out := &in.V6MainIP, &out.V6MainIP
		*out = new(string)
		**out = **in
	}
	if in.V6Network != nil {
		in, out := &in.V6Network, &out.V6Network
		*out = new(string)
		**out = **in
	}
	if in.V6NetworkSize != nil {
		in, out := &in.V6NetworkSize, &out.V6NetworkSize
		*out = new(int64)
		**out = **in
	}
	if in.VPCIds != nil {
		in, out := &in.VPCIds, &out.VPCIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.VPCOnly != nil {
		in, out := &in.VPCOnly, &out.VPCOnly
		*out = new(bool)
		**out = **in
	}
	if in.VcpuCount != nil {
		in, out := &in.VcpuCount, &out.VcpuCount
		*out = new(int64)
		**out = **in
	}
	if in.Vpc2Ids != nil {
		in, out := &in.Vpc2Ids, &out.Vpc2Ids
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceObservation.
func (in *InstanceObservation) DeepCopy() *InstanceObservation {
	if in == nil {
		return nil
	}
	out := new(InstanceObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceParameters) DeepCopyInto(out *InstanceParameters) {
	*out = *in
	if in.ActivationEmail != nil {
		in, out := &in.ActivationEmail, &out.ActivationEmail
		*out = new(bool)
		**out = **in
	}
	if in.AppID != nil {
		in, out := &in.AppID, &out.AppID
		*out = new(int64)
		**out = **in
	}
	if in.AppVariables != nil {
		in, out := &in.AppVariables, &out.AppVariables
		*out = make(map[string]*string, len(*in))
		for key, val := range *in {
			var outVal *string
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = new(string)
				**out = **in
			}
			(*out)[key] = outVal
		}
	}
	if in.Backups != nil {
		in, out := &in.Backups, &out.Backups
		*out = new(string)
		**out = **in
	}
	if in.BackupsSchedule != nil {
		in, out := &in.BackupsSchedule, &out.BackupsSchedule
		*out = new(BackupsScheduleParameters)
		(*in).DeepCopyInto(*out)
	}
	if in.BlockDevices != nil {
		in, out := &in.BlockDevices, &out.BlockDevices
		*out = make([]BlockDevicesParameters, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.DdosProtection != nil {
		in, out := &in.DdosProtection, &out.DdosProtection
		*out = new(bool)
		**out = **in
	}
	if in.DisablePublicIPv4 != nil {
		in, out := &in.DisablePublicIPv4, &out.DisablePublicIPv4
		*out = new(bool)
		**out = **in
	}
	if in.EnableIPv6 != nil {
		in, out := &in.EnableIPv6, &out.EnableIPv6
		*out = new(bool)
		**out = **in
	}
	if in.FirewallGroupID != nil {
		in, out := &in.FirewallGroupID, &out.FirewallGroupID
		*out = new(string)
		**out = **in
	}
	if in.FirewallGroupIDRef != nil {
		in, out := &in.FirewallGroupIDRef, &out.FirewallGroupIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.FirewallGroupIDSelector != nil {
		in, out := &in.FirewallGroupIDSelector, &out.FirewallGroupIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Hostname != nil {
		in, out := &in.Hostname, &out.Hostname
		*out = new(string)
		**out = **in
	}
	if in.ImageID != nil {
		in, out := &in.ImageID, &out.ImageID
		*out = new(string)
		**out = **in
	}
	if in.IpxeChainURL != nil {
		in, out := &in.IpxeChainURL, &out.IpxeChainURL
		*out = new(string)
		**out = **in
	}
	if in.IsoID != nil {
		in, out := &in.IsoID, &out.IsoID
		*out = new(string)
		**out = **in
	}
	if in.IsoIDRef != nil {
		in, out := &in.IsoIDRef, &out.IsoIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.IsoIDSelector != nil {
		in, out := &in.IsoIDSelector, &out.IsoIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Label != nil {
		in, out := &in.Label, &out.Label
		*out = new(string)
		**out = **in
	}
	if in.OsID != nil {
		in, out := &in.OsID, &out.OsID
		*out = new(int64)
		**out = **in
	}
	if in.Plan != nil {
		in, out := &in.Plan, &out.Plan
		*out = new(string)
		**out = **in
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	if in.ReservedIPID != nil {
		in, out := &in.ReservedIPID, &out.ReservedIPID
		*out = new(string)
		**out = **in
	}
	if in.ReservedIPIDRef != nil {
		in, out := &in.ReservedIPIDRef, &out.ReservedIPIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ReservedIPIDSelector != nil {
		in, out := &in.ReservedIPIDSelector, &out.ReservedIPIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.SSHKeyIds != nil {
		in, out := &in.SSHKeyIds, &out.SSHKeyIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.SSHKeyIdsRefs != nil {
		in, out := &in.SSHKeyIdsRefs, &out.SSHKeyIdsRefs
		*out = make([]v2.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.SSHKeyIdsSelector != nil {
		in, out := &in.SSHKeyIdsSelector, &out.SSHKeyIdsSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.ScriptID != nil {
		in, out := &in.ScriptID, &out.ScriptID
		*out = new(string)
		**out = **in
	}
	if in.ScriptIDRef != nil {
		in, out := &in.ScriptIDRef, &out.ScriptIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.ScriptIDSelector != nil {
		in, out := &in.ScriptIDSelector, &out.ScriptIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.SnapshotID != nil {
		in, out := &in.SnapshotID, &out.SnapshotID
		*out = new(string)
		**out = **in
	}
	if in.SnapshotIDRef != nil {
		in, out := &in.SnapshotIDRef, &out.SnapshotIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.SnapshotIDSelector != nil {
		in, out := &in.SnapshotIDSelector, &out.SnapshotIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.Tags != nil {
		in, out := &in.Tags, &out.Tags
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.UserData != nil {
		in, out := &in.UserData, &out.UserData
		*out = new(string)
		**out = **in
	}
	if in.UserScheme != nil {
		in, out := &in.UserScheme, &out.UserScheme
		*out = new(string)
		**out = **in
	}
	if in.VPCIds != nil {
		in, out := &in.VPCIds, &out.VPCIds
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
	if in.VPCIdsRefs != nil {
		in, out := &in.VPCIdsRefs, &out.VPCIdsRefs
		*out = make([]v2.Reference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.VPCIdsSelector != nil {
		in, out := &in.VPCIdsSelector, &out.VPCIdsSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
	if in.VPCOnly != nil {
		in, out := &in.VPCOnly, &out.VPCOnly
		*out = new(bool)
		**out = **in
	}
	if in.Vpc2Ids != nil {
		in, out := &in.Vpc2Ids, &out.Vpc2Ids
		*out = make([]*string, len(*in))
		for i := range *in {
			if (*in)[i] != nil {
				in, out := &(*in)[i], &(*out)[i]
				*out = new(string)
				**out = **in
			}
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceParameters.
func (in *InstanceParameters) DeepCopy() *InstanceParameters {
	if in == nil {
		return nil
	}
	out := new(InstanceParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceSpec) DeepCopyInto(out *InstanceSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceSpec.
func (in *InstanceSpec) DeepCopy() *InstanceSpec {
	if in == nil {
		return nil
	}
	out := new(InstanceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *InstanceStatus) DeepCopyInto(out *InstanceStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new InstanceStatus.
func (in *InstanceStatus) DeepCopy() *InstanceStatus {
	if in == nil {
		return nil
	}
	out := new(InstanceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHKey) DeepCopyInto(out *SSHKey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHKey.
func (in *SSHKey) DeepCopy() *SSHKey {
	if in == nil {
		return nil
	}
	out := new(SSHKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SSHKey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHKeyInitParameters) DeepCopyInto(out *SSHKeyInitParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.SSHKey != nil {
		in, out := &in.SSHKey, &out.SSHKey
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHKeyInitParameters.
func (in *SSHKeyInitParameters) DeepCopy() *SSHKeyInitParameters {
	if in == nil {
		return nil
	}
	out := new(SSHKeyInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHKeyList) DeepCopyInto(out *SSHKeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SSHKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHKeyList.
func (in *SSHKeyList) DeepCopy() *SSHKeyList {
	if in == nil {
		return nil
	}
	out := new(SSHKeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SSHKeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHKeyObservation) DeepCopyInto(out *SSHKeyObservation) {
	*out = *in
	if in.DateCreated != nil {
		in, out := &in.DateCreated, &out.DateCreated
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.SSHKey != nil {
		in, out := &in.SSHKey, &out.SSHKey
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHKeyObservation.
func (in *SSHKeyObservation) DeepCopy() *SSHKeyObservation {
	if in == nil {
		return nil
	}
	out := new(SSHKeyObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHKeyParameters) DeepCopyInto(out *SSHKeyParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.SSHKey != nil {
		in, out := &in.SSHKey, &out.SSHKey
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHKeyParameters.
func (in *SSHKeyParameters) DeepCopy() *SSHKeyParameters {
	if in == nil {
		return nil
	}
	out := new(SSHKeyParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHKeySpec) DeepCopyInto(out *SSHKeySpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHKeySpec.
func (in *SSHKeySpec) DeepCopy() *SSHKeySpec {
	if in == nil {
		return nil
	}
	out := new(SSHKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SSHKeyStatus) DeepCopyInto(out *SSHKeyStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SSHKeyStatus.
func (in *SSHKeyStatus) DeepCopy() *SSHKeyStatus {
	if in == nil {
		return nil
	}
	out := new(SSHKeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Snapshot) DeepCopyInto(out *Snapshot) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Snapshot.
func (in *Snapshot) DeepCopy() *Snapshot {
	if in == nil {
		return nil
	}
	out := new(Snapshot)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Snapshot) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotFromURL) DeepCopyInto(out *SnapshotFromURL) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotFromURL.
func (in *SnapshotFromURL) DeepCopy() *SnapshotFromURL {
	if in == nil {
		return nil
	}
	out := new(SnapshotFromURL)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SnapshotFromURL) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotFromURLInitParameters) DeepCopyInto(out *SnapshotFromURLInitParameters) {
	*out = *in
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.UseUefi != nil {
		in, out := &in.UseUefi, &out.UseUefi
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotFromURLInitParameters.
func (in *SnapshotFromURLInitParameters) DeepCopy() *SnapshotFromURLInitParameters {
	if in == nil {
		return nil
	}
	out := new(SnapshotFromURLInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotFromURLList) DeepCopyInto(out *SnapshotFromURLList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SnapshotFromURL, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotFromURLList.
func (in *SnapshotFromURLList) DeepCopy() *SnapshotFromURLList {
	if in == nil {
		return nil
	}
	out := new(SnapshotFromURLList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SnapshotFromURLList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotFromURLObservation) DeepCopyInto(out *SnapshotFromURLObservation) {
	*out = *in
	if in.AppID != nil {
		in, out := &in.AppID, &out.AppID
		*out = new(int64)
		**out = **in
	}
	if in.DateCreated != nil {
		in, out := &in.DateCreated, &out.DateCreated
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.OsID != nil {
		in, out := &in.OsID, &out.OsID
		*out = new(int64)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(int64)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.UseUefi != nil {
		in, out := &in.UseUefi, &out.UseUefi
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotFromURLObservation.
func (in *SnapshotFromURLObservation) DeepCopy() *SnapshotFromURLObservation {
	if in == nil {
		return nil
	}
	out := new(SnapshotFromURLObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotFromURLParameters) DeepCopyInto(out *SnapshotFromURLParameters) {
	*out = *in
	if in.URL != nil {
		in, out := &in.URL, &out.URL
		*out = new(string)
		**out = **in
	}
	if in.UseUefi != nil {
		in, out := &in.UseUefi, &out.UseUefi
		*out = new(bool)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotFromURLParameters.
func (in *SnapshotFromURLParameters) DeepCopy() *SnapshotFromURLParameters {
	if in == nil {
		return nil
	}
	out := new(SnapshotFromURLParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotFromURLSpec) DeepCopyInto(out *SnapshotFromURLSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotFromURLSpec.
func (in *SnapshotFromURLSpec) DeepCopy() *SnapshotFromURLSpec {
	if in == nil {
		return nil
	}
	out := new(SnapshotFromURLSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotFromURLStatus) DeepCopyInto(out *SnapshotFromURLStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotFromURLStatus.
func (in *SnapshotFromURLStatus) DeepCopy() *SnapshotFromURLStatus {
	if in == nil {
		return nil
	}
	out := new(SnapshotFromURLStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotInitParameters) DeepCopyInto(out *SnapshotInitParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.InstanceID != nil {
		in, out := &in.InstanceID, &out.InstanceID
		*out = new(string)
		**out = **in
	}
	if in.InstanceIDRef != nil {
		in, out := &in.InstanceIDRef, &out.InstanceIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.InstanceIDSelector != nil {
		in, out := &in.InstanceIDSelector, &out.InstanceIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotInitParameters.
func (in *SnapshotInitParameters) DeepCopy() *SnapshotInitParameters {
	if in == nil {
		return nil
	}
	out := new(SnapshotInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotList) DeepCopyInto(out *SnapshotList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]Snapshot, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotList.
func (in *SnapshotList) DeepCopy() *SnapshotList {
	if in == nil {
		return nil
	}
	out := new(SnapshotList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SnapshotList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotObservation) DeepCopyInto(out *SnapshotObservation) {
	*out = *in
	if in.AppID != nil {
		in, out := &in.AppID, &out.AppID
		*out = new(int64)
		**out = **in
	}
	if in.DateCreated != nil {
		in, out := &in.DateCreated, &out.DateCreated
		*out = new(string)
		**out = **in
	}
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.InstanceID != nil {
		in, out := &in.InstanceID, &out.InstanceID
		*out = new(string)
		**out = **in
	}
	if in.OsID != nil {
		in, out := &in.OsID, &out.OsID
		*out = new(int64)
		**out = **in
	}
	if in.Size != nil {
		in, out := &in.Size, &out.Size
		*out = new(int64)
		**out = **in
	}
	if in.Status != nil {
		in, out := &in.Status, &out.Status
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotObservation.
func (in *SnapshotObservation) DeepCopy() *SnapshotObservation {
	if in == nil {
		return nil
	}
	out := new(SnapshotObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotParameters) DeepCopyInto(out *SnapshotParameters) {
	*out = *in
	if in.Description != nil {
		in, out := &in.Description, &out.Description
		*out = new(string)
		**out = **in
	}
	if in.InstanceID != nil {
		in, out := &in.InstanceID, &out.InstanceID
		*out = new(string)
		**out = **in
	}
	if in.InstanceIDRef != nil {
		in, out := &in.InstanceIDRef, &out.InstanceIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	if in.InstanceIDSelector != nil {
		in, out := &in.InstanceIDSelector, &out.InstanceIDSelector
		*out = new(v2.Selector)
		(*in).DeepCopyInto(*out)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotParameters.
func (in *SnapshotParameters) DeepCopy() *SnapshotParameters {
	if in == nil {
		return nil
	}
	out := new(SnapshotParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotSpec) DeepCopyInto(out *SnapshotSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotSpec.
func (in *SnapshotSpec) DeepCopy() *SnapshotSpec {
	if in == nil {
		return nil
	}
	out := new(SnapshotSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SnapshotStatus) DeepCopyInto(out *SnapshotStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SnapshotStatus.
func (in *SnapshotStatus) DeepCopy() *SnapshotStatus {
	if in == nil {
		return nil
	}
	out := new(SnapshotStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StartupScript) DeepCopyInto(out *StartupScript) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartupScript.
func (in *StartupScript) DeepCopy() *StartupScript {
	if in == nil {
		return nil
	}
	out := new(StartupScript)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StartupScript) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StartupScriptInitParameters) DeepCopyInto(out *StartupScriptInitParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Script != nil {
		in, out := &in.Script, &out.Script
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartupScriptInitParameters.
func (in *StartupScriptInitParameters) DeepCopy() *StartupScriptInitParameters {
	if in == nil {
		return nil
	}
	out := new(StartupScriptInitParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StartupScriptList) DeepCopyInto(out *StartupScriptList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]StartupScript, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartupScriptList.
func (in *StartupScriptList) DeepCopy() *StartupScriptList {
	if in == nil {
		return nil
	}
	out := new(StartupScriptList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *StartupScriptList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StartupScriptObservation) DeepCopyInto(out *StartupScriptObservation) {
	*out = *in
	if in.DateCreated != nil {
		in, out := &in.DateCreated, &out.DateCreated
		*out = new(string)
		**out = **in
	}
	if in.DateModified != nil {
		in, out := &in.DateModified, &out.DateModified
		*out = new(string)
		**out = **in
	}
	if in.ID != nil {
		in, out := &in.ID, &out.ID
		*out = new(string)
		**out = **in
	}
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Script != nil {
		in, out := &in.Script, &out.Script
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartupScriptObservation.
func (in *StartupScriptObservation) DeepCopy() *StartupScriptObservation {
	if in == nil {
		return nil
	}
	out := new(StartupScriptObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StartupScriptParameters) DeepCopyInto(out *StartupScriptParameters) {
	*out = *in
	if in.Name != nil {
		in, out := &in.Name, &out.Name
		*out = new(string)
		**out = **in
	}
	if in.Script != nil {
		in, out := &in.Script, &out.Script
		*out = new(string)
		**out = **in
	}
	if in.Type != nil {
		in, out := &in.Type, &out.Type
		*out = new(string)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartupScriptParameters.
func (in *StartupScriptParameters) DeepCopy() *StartupScriptParameters {
	if in == nil {
		return nil
	}
	out := new(StartupScriptParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StartupScriptSpec) DeepCopyInto(out *StartupScriptSpec) {
	*out = *in
	in.ClusterManagedResourceSpec.DeepCopyInto(&out.ClusterManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
	in.InitProvider.DeepCopyInto(&out.InitProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartupScriptSpec.
func (in *StartupScriptSpec) DeepCopy() *StartupScriptSpec {
	if in == nil {
		return nil
	}
	out := new(StartupScriptSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StartupScriptStatus) DeepCopyInto(out *StartupScriptStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StartupScriptStatus.
func (in *StartupScriptStatus) DeepCopy() *StartupScriptStatus {
	if in == nil {
		return nil
	}
	out := new(StartupScriptStatus)
	in.DeepCopyInto(out)
	return out
}
