// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type InstanceIPv4InitParameters struct {

	// The ID of the instance to be assigned the IPv4 address.
	// +crossplane:generate:reference:type=github.com/upbound/provider-vultr/apis/cluster/compute/v1beta1.Instance
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a Instance in compute to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v2.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in compute to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v2.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// Default true. Determines whether or not the server is rebooted after adding the IPv4 address.
	Reboot *bool `json:"reboot,omitempty" tf:"reboot,omitempty"`
}

type InstanceIPv4Observation struct {

	// The gateway IP address.
	Gateway *string `json:"gateway,omitempty" tf:"gateway,omitempty"`

	// The ID is the IPv4 address in canonical format.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The IPv4 address in canonical format.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// The ID of the instance to be assigned the IPv4 address.
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// The IPv4 netmask in dot-decimal notation.
	Netmask *string `json:"netmask,omitempty" tf:"netmask,omitempty"`

	// Default true. Determines whether or not the server is rebooted after adding the IPv4 address.
	Reboot *bool `json:"reboot,omitempty" tf:"reboot,omitempty"`

	// The reverse DNS information for this IP address.
	Reverse *string `json:"reverse,omitempty" tf:"reverse,omitempty"`
}

type InstanceIPv4Parameters struct {

	// The ID of the instance to be assigned the IPv4 address.
	// +crossplane:generate:reference:type=github.com/upbound/provider-vultr/apis/cluster/compute/v1beta1.Instance
	// +kubebuilder:validation:Optional
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a Instance in compute to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v2.Reference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in compute to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v2.Selector `json:"instanceIdSelector,omitempty" tf:"-"`

	// Default true. Determines whether or not the server is rebooted after adding the IPv4 address.
	// +kubebuilder:validation:Optional
	Reboot *bool `json:"reboot,omitempty" tf:"reboot,omitempty"`
}

// InstanceIPv4Spec defines the desired state of InstanceIPv4
type InstanceIPv4Spec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   InstanceIPv4Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider InstanceIPv4InitParameters `json:"initProvider,omitempty"`
}

// InstanceIPv4Status defines the observed state of InstanceIPv4.
type InstanceIPv4Status struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               InstanceIPv4Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// InstanceIPv4 is the Schema for the InstanceIPv4s API. Provides a instance IPv4 resource. This can be used to create, read, and modify a IPv4 address.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vultr}
type InstanceIPv4 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              InstanceIPv4Spec   `json:"spec"`
	Status            InstanceIPv4Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// InstanceIPv4List contains a list of InstanceIPv4s
type InstanceIPv4List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []InstanceIPv4 `json:"items"`
}

// Repository type metadata.
var (
	InstanceIPv4_Kind             = "InstanceIPv4"
	InstanceIPv4_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: InstanceIPv4_Kind}.String()
	InstanceIPv4_KindAPIVersion   = InstanceIPv4_Kind + "." + CRDGroupVersion.String()
	InstanceIPv4_GroupVersionKind = CRDGroupVersion.WithKind(InstanceIPv4_Kind)
)

func init() {
	SchemeBuilder.Register(&InstanceIPv4{}, &InstanceIPv4List{})
}
