// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type SnapshotFromURLInitParameters struct {

	// URL of the given resource you want to create a snapshot from.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// Whether or not to use UEFI when creating the snapshot.
	UseUefi *bool `json:"useUefi,omitempty" tf:"use_uefi,omitempty"`
}

type SnapshotFromURLObservation struct {

	// The app id which the snapshot is associated with.
	AppID *int64 `json:"appId,omitempty" tf:"app_id,omitempty"`

	// The date the snapshot was created.
	DateCreated *string `json:"dateCreated,omitempty" tf:"date_created,omitempty"`

	// The description for the given snapshot.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID for the given snapshot.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The os id which the snapshot is associated with.
	OsID *int64 `json:"osId,omitempty" tf:"os_id,omitempty"`

	// The size of the snapshot in Bytes.
	Size *int64 `json:"size,omitempty" tf:"size,omitempty"`

	// The status for the given snapshot.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// URL of the given resource you want to create a snapshot from.
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// Whether or not to use UEFI when creating the snapshot.
	UseUefi *bool `json:"useUefi,omitempty" tf:"use_uefi,omitempty"`
}

type SnapshotFromURLParameters struct {

	// URL of the given resource you want to create a snapshot from.
	// +kubebuilder:validation:Optional
	URL *string `json:"url,omitempty" tf:"url,omitempty"`

	// Whether or not to use UEFI when creating the snapshot.
	// +kubebuilder:validation:Optional
	UseUefi *bool `json:"useUefi,omitempty" tf:"use_uefi,omitempty"`
}

// SnapshotFromURLSpec defines the desired state of SnapshotFromURL
type SnapshotFromURLSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   SnapshotFromURLParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider SnapshotFromURLInitParameters `json:"initProvider,omitempty"`
}

// SnapshotFromURLStatus defines the observed state of SnapshotFromURL.
type SnapshotFromURLStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               SnapshotFromURLObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// SnapshotFromURL is the Schema for the SnapshotFromURLs API. Provides a Vultr Snapshots from URL resource. This can be used to create, read, modify, and delete Snapshots from URL.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vultr}
type SnapshotFromURL struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.url) || (has(self.initProvider) && has(self.initProvider.url))",message="spec.forProvider.url is a required parameter"
	Spec   SnapshotFromURLSpec   `json:"spec"`
	Status SnapshotFromURLStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// SnapshotFromURLList contains a list of SnapshotFromURLs
type SnapshotFromURLList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []SnapshotFromURL `json:"items"`
}

// Repository type metadata.
var (
	SnapshotFromURL_Kind             = "SnapshotFromURL"
	SnapshotFromURL_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: SnapshotFromURL_Kind}.String()
	SnapshotFromURL_KindAPIVersion   = SnapshotFromURL_Kind + "." + CRDGroupVersion.String()
	SnapshotFromURL_GroupVersionKind = CRDGroupVersion.WithKind(SnapshotFromURL_Kind)
)

func init() {
	SchemeBuilder.Register(&SnapshotFromURL{}, &SnapshotFromURLList{})
}
