apiVersion: vultr.m.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  name: default
  namespace: upbound-system
spec:
  credentials:
    source: Secret
    # The secret reference is namespace-local: it resolves to the namespace of
    # the referencing managed resource.
    secretRef:
      name: vultr-creds
      key: creds
