// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type KubernetesNodePoolInitParameters struct {

	// Enable the auto scaler for the default node pool.
	AutoScaler *bool `json:"autoScaler,omitempty" tf:"auto_scaler,omitempty"`

	// The VKE cluster ID you want to attach this nodepool to.
	// +crossplane:generate:reference:type=github.com/upbound/provider-vultr/apis/cluster/vke/v1beta1.Kubernetes
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Kubernetes in vke to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Kubernetes in vke to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// The label to be used as a prefix for nodes in this node pool.
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	Labels []KubernetesNodePoolLabelsInitParameters `json:"labels,omitempty" tf:"labels,omitempty"`

	// The maximum number of nodes to use with the auto scaler.
	MaxNodes *int64 `json:"maxNodes,omitempty" tf:"max_nodes,omitempty"`

	// The minimum number of nodes to use with the auto scaler.
	MinNodes *int64 `json:"minNodes,omitempty" tf:"min_nodes,omitempty"`

	// The number of nodes in this node pool.
	NodeQuantity *int64 `json:"nodeQuantity,omitempty" tf:"node_quantity,omitempty"`

	// The plan to be used in this node pool. See plans list Note the minimum plan requirements must have at least 1 core and 2 gbs of memory.
	Plan *string `json:"plan,omitempty" tf:"plan,omitempty"`

	// A tag that is assigned to this node pool.
	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`

	Taints []KubernetesNodePoolTaintsInitParameters `json:"taints,omitempty" tf:"taints,omitempty"`

	// A base64 encoded string containing the user data to apply to nodes in the node pool.
	UserData *string `json:"userData,omitempty" tf:"user_data,omitempty"`
}

type KubernetesNodePoolLabelsInitParameters struct {

	// The key definining the label for kubernetes.
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// The value of the label for kubernetes.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type KubernetesNodePoolLabelsObservation struct {

	// The Nodepool ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The key definining the label for kubernetes.
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// The value of the label for kubernetes.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type KubernetesNodePoolLabelsParameters struct {

	// The key definining the label for kubernetes.
	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// The value of the label for kubernetes.
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type KubernetesNodePoolNodesInitParameters struct {
}

type KubernetesNodePoolNodesObservation struct {

	// Date of node pool creation.
	DateCreated *string `json:"dateCreated,omitempty" tf:"date_created,omitempty"`

	// The Nodepool ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The label to be used as a prefix for nodes in this node pool.
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// Status of node pool.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`
}

type KubernetesNodePoolNodesParameters struct {
}

type KubernetesNodePoolObservation struct {

	// Enable the auto scaler for the default node pool.
	AutoScaler *bool `json:"autoScaler,omitempty" tf:"auto_scaler,omitempty"`

	// The VKE cluster ID you want to attach this nodepool to.
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Date of node pool creation.
	DateCreated *string `json:"dateCreated,omitempty" tf:"date_created,omitempty"`

	// Date of node pool updates.
	DateUpdated *string `json:"dateUpdated,omitempty" tf:"date_updated,omitempty"`

	// The Nodepool ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The label to be used as a prefix for nodes in this node pool.
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	Labels []KubernetesNodePoolLabelsObservation `json:"labels,omitempty" tf:"labels,omitempty"`

	// The maximum number of nodes to use with the auto scaler.
	MaxNodes *int64 `json:"maxNodes,omitempty" tf:"max_nodes,omitempty"`

	// The minimum number of nodes to use with the auto scaler.
	MinNodes *int64 `json:"minNodes,omitempty" tf:"min_nodes,omitempty"`

	// The number of nodes in this node pool.
	NodeQuantity *int64 `json:"nodeQuantity,omitempty" tf:"node_quantity,omitempty"`

	Nodes []KubernetesNodePoolNodesObservation `json:"nodes,omitempty" tf:"nodes,omitempty"`

	// The plan to be used in this node pool. See plans list Note the minimum plan requirements must have at least 1 core and 2 gbs of memory.
	Plan *string `json:"plan,omitempty" tf:"plan,omitempty"`

	// Status of node pool.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// A tag that is assigned to this node pool.
	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`

	Taints []KubernetesNodePoolTaintsObservation `json:"taints,omitempty" tf:"taints,omitempty"`

	// A base64 encoded string containing the user data to apply to nodes in the node pool.
	UserData *string `json:"userData,omitempty" tf:"user_data,omitempty"`
}

type KubernetesNodePoolParameters struct {

	// Enable the auto scaler for the default node pool.
	// +kubebuilder:validation:Optional
	AutoScaler *bool `json:"autoScaler,omitempty" tf:"auto_scaler,omitempty"`

	// The VKE cluster ID you want to attach this nodepool to.
	// +crossplane:generate:reference:type=github.com/upbound/provider-vultr/apis/cluster/vke/v1beta1.Kubernetes
	// +kubebuilder:validation:Optional
	ClusterID *string `json:"clusterId,omitempty" tf:"cluster_id,omitempty"`

	// Reference to a Kubernetes in vke to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDRef *v2.Reference `json:"clusterIdRef,omitempty" tf:"-"`

	// Selector for a Kubernetes in vke to populate clusterId.
	// +kubebuilder:validation:Optional
	ClusterIDSelector *v2.Selector `json:"clusterIdSelector,omitempty" tf:"-"`

	// The label to be used as a prefix for nodes in this node pool.
	// +kubebuilder:validation:Optional
	Label *string `json:"label,omitempty" tf:"label,omitempty"`

	// +kubebuilder:validation:Optional
	Labels []KubernetesNodePoolLabelsParameters `json:"labels,omitempty" tf:"labels,omitempty"`

	// The maximum number of nodes to use with the auto scaler.
	// +kubebuilder:validation:Optional
	MaxNodes *int64 `json:"maxNodes,omitempty" tf:"max_nodes,omitempty"`

	// The minimum number of nodes to use with the auto scaler.
	// +kubebuilder:validation:Optional
	MinNodes *int64 `json:"minNodes,omitempty" tf:"min_nodes,omitempty"`

	// The number of nodes in this node pool.
	// +kubebuilder:validation:Optional
	NodeQuantity *int64 `json:"nodeQuantity,omitempty" tf:"node_quantity,omitempty"`

	// The plan to be used in this node pool. See plans list Note the minimum plan requirements must have at least 1 core and 2 gbs of memory.
	// +kubebuilder:validation:Optional
	Plan *string `json:"plan,omitempty" tf:"plan,omitempty"`

	// A tag that is assigned to this node pool.
	// +kubebuilder:validation:Optional
	Tag *string `json:"tag,omitempty" tf:"tag,omitempty"`

	// +kubebuilder:validation:Optional
	Taints []KubernetesNodePoolTaintsParameters `json:"taints,omitempty" tf:"taints,omitempty"`

	// A base64 encoded string containing the user data to apply to nodes in the node pool.
	// +kubebuilder:validation:Optional
	UserData *string `json:"userData,omitempty" tf:"user_data,omitempty"`
}

type KubernetesNodePoolTaintsInitParameters struct {

	// The effect of the taint for kubernetes.  Must be one of NoSchedule, PreferNoSchedule or NoExecute.
	Effect *string `json:"effect,omitempty" tf:"effect,omitempty"`

	// The key definining the label for kubernetes.
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// The value of the label for kubernetes.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type KubernetesNodePoolTaintsObservation struct {

	// The effect of the taint for kubernetes.  Must be one of NoSchedule, PreferNoSchedule or NoExecute.
	Effect *string `json:"effect,omitempty" tf:"effect,omitempty"`

	// The Nodepool ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The key definining the label for kubernetes.
	Key *string `json:"key,omitempty" tf:"key,omitempty"`

	// The value of the label for kubernetes.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type KubernetesNodePoolTaintsParameters struct {

	// The effect of the taint for kubernetes.  Must be one of NoSchedule, PreferNoSchedule or NoExecute.
	// +kubebuilder:validation:Optional
	Effect *string `json:"effect" tf:"effect,omitempty"`

	// The key definining the label for kubernetes.
	// +kubebuilder:validation:Optional
	Key *string `json:"key" tf:"key,omitempty"`

	// The value of the label for kubernetes.
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

// KubernetesNodePoolSpec defines the desired state of KubernetesNodePool
type KubernetesNodePoolSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   KubernetesNodePoolParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider KubernetesNodePoolInitParameters `json:"initProvider,omitempty"`
}

// KubernetesNodePoolStatus defines the observed state of KubernetesNodePool.
type KubernetesNodePoolStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               KubernetesNodePoolObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// KubernetesNodePool is the Schema for the KubernetesNodePools API. Provides a Vultr Kubernetes Engine (VKE) Node Pool resource. This can be used to create, read, modify, and delete VKE clusters on your Vultr account.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vultr}
type KubernetesNodePool struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.label) || (has(self.initProvider) && has(self.initProvider.label))",message="spec.forProvider.label is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.nodeQuantity) || (has(self.initProvider) && has(self.initProvider.nodeQuantity))",message="spec.forProvider.nodeQuantity is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.plan) || (has(self.initProvider) && has(self.initProvider.plan))",message="spec.forProvider.plan is a required parameter"
	Spec   KubernetesNodePoolSpec   `json:"spec"`
	Status KubernetesNodePoolStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// KubernetesNodePoolList contains a list of KubernetesNodePools
type KubernetesNodePoolList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []KubernetesNodePool `json:"items"`
}

// Repository type metadata.
var (
	KubernetesNodePool_Kind             = "KubernetesNodePool"
	KubernetesNodePool_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: KubernetesNodePool_Kind}.String()
	KubernetesNodePool_KindAPIVersion   = KubernetesNodePool_Kind + "." + CRDGroupVersion.String()
	KubernetesNodePool_GroupVersionKind = CRDGroupVersion.WithKind(KubernetesNodePool_Kind)
)

func init() {
	SchemeBuilder.Register(&KubernetesNodePool{}, &KubernetesNodePoolList{})
}
