apiVersion: network.vultr.m.upbound.io/v1beta1
kind: NATGateway
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/natgateway
  labels:
    testing.upbound.io/example-name: my_nat_gateway
  name: my-nat-gateway
  namespace: upbound-system
spec:
  forProvider:
    label: my_nat_gateway
    tag: my tag
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: my_vpc
