apiVersion: network.vultr.m.upbound.io/v1beta1
kind: ReverseIPv4
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/reverseipv4
  labels:
    testing.upbound.io/example-name: my_reverse_ipv4
  name: my-reverse-ipv4
  namespace: upbound-system
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: my_instance
    ipSelector:
      matchLabels:
        testing.upbound.io/example-name: my_instance
    reverse: host.example.com

---

apiVersion: compute.vultr.m.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/reverseipv4
  labels:
    testing.upbound.io/example-name: my_instance
  name: my-instance
  namespace: upbound-system
spec:
  forProvider:
    enableIpv6: true
    osId: 477
    plan: vc2-1c-2gb
    region: ewr
