apiVersion: network.vultr.m.upbound.io/v1beta1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/vpc
  labels:
    testing.upbound.io/example-name: my_vpc
  name: my-vpc
  namespace: upbound-system
spec:
  forProvider:
    description: my vpc
    region: ewr
