apiVersion: vke.vultr.upbound.io/v1beta1
kind: Kubernetes
metadata:
  annotations:
    meta.upbound.io/example-id: vke/v1beta1/kubernetes
  labels:
    testing.upbound.io/example-name: example-vke
  name: example-vke
spec:
  forProvider:
    label: example-vke
    region: ewr
    version: v1.36.1+3
    haControlplanes: true
    nodePools:
      label: example-vke-pool
      plan: vc2-1c-2gb
      nodeQuantity: 1
      autoScaler: true
      minNodes: 1
      maxNodes: 2
      labels:
        - key: example.upbound.io/pool
          value: system
  writeConnectionSecretToRef:
    name: example-vke-kubeconfig
    namespace: upbound-system
