apiVersion: vke.vultr.upbound.io/v1beta1
kind: KubernetesNodePool
metadata:
  annotations:
    meta.upbound.io/example-id: vke/v1beta1/kubernetesnodepool
    uptest.upbound.io/timeout: "1800"
  labels:
    testing.upbound.io/example-name: example-vke-nodepool
  name: example-vke-nodepool
spec:
  forProvider:
    clusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-vke-nodepool
    label: example-vke-nodepool
    plan: vc2-1c-2gb
    nodeQuantity: 1

---

apiVersion: vke.vultr.upbound.io/v1beta1
kind: Kubernetes
metadata:
  annotations:
    meta.upbound.io/example-id: vke/v1beta1/kubernetesnodepool
  labels:
    testing.upbound.io/example-name: example-vke-nodepool
  name: example-vke-nodepool
spec:
  forProvider:
    label: example-vke-nodepool
    region: ewr
    version: v1.36.1+3
    nodePools:
      label: example-vke-pool
      plan: vc2-1c-2gb
      nodeQuantity: 1
