apiVersion: network.vultr.upbound.io/v1beta1
kind: DNSRecord
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/dnsrecord
  labels:
    testing.upbound.io/example-name: example-record
  name: example-record
spec:
  forProvider:
    domainSelector:
      matchLabels:
        testing.upbound.io/example-name: example-record
    name: www
    type: A
    data: 192.0.2.10
    ttl: 300

---

apiVersion: network.vultr.upbound.io/v1beta1
kind: DNSDomain
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/dnsrecord
    crossplane.io/external-name: uptest-example-records.com
  labels:
    testing.upbound.io/example-name: example-record
  name: example-record
spec:
  forProvider: {}
