apiVersion: storage.vultr.upbound.io/v1beta1
kind: ContainerRegistry
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/containerregistry
  labels:
    testing.upbound.io/example-name: example-registry
  name: example-registry
spec:
  forProvider:
    name: uptestvultrcr26
    plan: start_up
    public: false
    region: sjc
