apiVersion: network.vultr.upbound.io/v1beta1
kind: DNSRecord
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/dnsrecord
  labels:
    testing.upbound.io/example-name: my_record
  name: my-record
spec:
  forProvider:
    data: 66.42.94.227
    domainSelector:
      matchLabels:
        testing.upbound.io/example-name: my_domain
    name: www
    type: A

---

apiVersion: network.vultr.upbound.io/v1beta1
kind: DNSDomain
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/dnsrecord
  labels:
    testing.upbound.io/example-name: my_domain
  name: my-domain
spec:
  forProvider:
    ip: 66.42.94.227
