apiVersion: network.vultr.upbound.io/v1beta1
kind: NATGatewayPortForwardingRule
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/natgatewayportforwardingrule
  labels:
    testing.upbound.io/example-name: my_port_forwarding_rule
  name: my-port-forwarding-rule
spec:
  forProvider:
    description: my description
    enabled: true
    externalPort: "123"
    internalIp: 10.1.2.3
    internalPort: "321"
    name: my_port_forwarding_rule
    natGatewayIdSelector:
      matchLabels:
        testing.upbound.io/example-name: my_nat_gateway
    protocol: tcp
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: my_nat_gateway
