apiVersion: network.vultr.upbound.io/v1beta1
kind: ReservedIP
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/reservedip
  labels:
    testing.upbound.io/example-name: my_reserved_ip
  name: my-reserved-ip
spec:
  forProvider:
    ipType: v4
    label: my-reserved-ip
    region: sea
