apiVersion: iam.vultr.upbound.io/v1beta1
kind: User
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/user
  labels:
    testing.upbound.io/example-name: example-user
  name: example-user
spec:
  forProvider:
    name: example-user
    email: ${Rand.RFC1123Subdomain}@example.com
    passwordSecretRef:
      name: example-user-password
      namespace: upbound-system
      key: password
  initProvider:
    passwordSecretRef:
      name: example-user-password
      namespace: upbound-system
      key: password

---

apiVersion: v1
kind: Secret
metadata:
  name: example-user-password
  namespace: upbound-system
  labels:
    testing.upbound.io/example-name: example-user
type: Opaque
stringData:
  password: SuperSecure-Passw0rd!26
