apiVersion: network.vultr.m.upbound.io/v1beta1
kind: NATGateway
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/natgateway
  labels:
    testing.upbound.io/example-name: example-natgw
  name: example-natgw
  namespace: upbound-system
spec:
  forProvider:
    label: example-nat-gateway
    vpcIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-natgw

---

apiVersion: network.vultr.m.upbound.io/v1beta1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/natgateway
  labels:
    testing.upbound.io/example-name: example-natgw
  name: example-natgw
  namespace: upbound-system
spec:
  forProvider:
    description: example-natgw
    region: ewr
    v4Subnet: 10.2.0.0
    v4SubnetMask: 24
