apiVersion: network.vultr.m.upbound.io/v1beta1
kind: ReverseIPv4
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/reverseipv4
  labels:
    testing.upbound.io/example-name: example-reverseipv4
  name: example-reverseipv4
  namespace: upbound-system
spec:
  forProvider:
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example-reverseipv4
    ipSelector:
      matchLabels:
        testing.upbound.io/example-name: example-reverseipv4
    reverse: host-v4.example.com

---

apiVersion: compute.vultr.m.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/reverseipv4
    uptest.upbound.io/pre-delete-hook: ../testhooks/delete-reverseip.sh
  labels:
    testing.upbound.io/example-name: example-reverseipv4
  name: example-reverseipv4
  namespace: upbound-system
spec:
  forProvider:
    label: example-reverseipv4
    region: ewr
    plan: vc2-1c-1gb
    osId: 2136
