apiVersion: network.vultr.m.upbound.io/v1beta1
kind: VPC
metadata:
  annotations:
    meta.upbound.io/example-id: network/v1beta1/vpc
  labels:
    testing.upbound.io/example-name: example-vpc
  name: example-vpc
  namespace: upbound-system
spec:
  forProvider:
    description: example vpc
    region: ewr
    v4Subnet: 10.0.0.0
    v4SubnetMask: 24
