// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type OIDCProviderInitParameters struct {
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type OIDCProviderObservation struct {
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	IssuerID *string `json:"issuerId,omitempty" tf:"issuer_id,omitempty"`

	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type OIDCProviderParameters struct {

	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// OIDCProviderSpec defines the desired state of OIDCProvider
type OIDCProviderSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            OIDCProviderParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OIDCProviderInitParameters `json:"initProvider,omitempty"`
}

// OIDCProviderStatus defines the observed state of OIDCProvider.
type OIDCProviderStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               OIDCProviderObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// OIDCProvider is the Schema for the OIDCProviders API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,vultr}
type OIDCProvider struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   OIDCProviderSpec   `json:"spec"`
	Status OIDCProviderStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OIDCProviderList contains a list of OIDCProviders
type OIDCProviderList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OIDCProvider `json:"items"`
}

// Repository type metadata.
var (
	OIDCProvider_Kind             = "OIDCProvider"
	OIDCProvider_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OIDCProvider_Kind}.String()
	OIDCProvider_KindAPIVersion   = OIDCProvider_Kind + "." + CRDGroupVersion.String()
	OIDCProvider_GroupVersionKind = CRDGroupVersion.WithKind(OIDCProvider_Kind)
)

func init() {
	SchemeBuilder.Register(&OIDCProvider{}, &OIDCProviderList{})
}
