// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type OrganizationPolicyUserAttachmentInitParameters struct {

	// The ID of the policy.
	// +crossplane:generate:reference:type=github.com/upbound/provider-vultr/apis/namespaced/iam/v1beta1.OrganizationPolicy
	PolicyID *string `json:"policyId,omitempty" tf:"policy_id,omitempty"`

	// Reference to a OrganizationPolicy in iam to populate policyId.
	// +kubebuilder:validation:Optional
	PolicyIDRef *v2.NamespacedReference `json:"policyIdRef,omitempty" tf:"-"`

	// Selector for a OrganizationPolicy in iam to populate policyId.
	// +kubebuilder:validation:Optional
	PolicyIDSelector *v2.NamespacedSelector `json:"policyIdSelector,omitempty" tf:"-"`

	// The ID of the user.
	// +crossplane:generate:reference:type=github.com/upbound/provider-vultr/apis/namespaced/iam/v1beta1.User
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// Reference to a User in iam to populate userId.
	// +kubebuilder:validation:Optional
	UserIDRef *v2.NamespacedReference `json:"userIdRef,omitempty" tf:"-"`

	// Selector for a User in iam to populate userId.
	// +kubebuilder:validation:Optional
	UserIDSelector *v2.NamespacedSelector `json:"userIdSelector,omitempty" tf:"-"`
}

type OrganizationPolicyUserAttachmentObservation struct {

	// The ID of the policy user attachment (a composite of the policy_id and user_id).
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the policy.
	PolicyID *string `json:"policyId,omitempty" tf:"policy_id,omitempty"`

	// The ID of the user.
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`
}

type OrganizationPolicyUserAttachmentParameters struct {

	// The ID of the policy.
	// +crossplane:generate:reference:type=github.com/upbound/provider-vultr/apis/namespaced/iam/v1beta1.OrganizationPolicy
	// +kubebuilder:validation:Optional
	PolicyID *string `json:"policyId,omitempty" tf:"policy_id,omitempty"`

	// Reference to a OrganizationPolicy in iam to populate policyId.
	// +kubebuilder:validation:Optional
	PolicyIDRef *v2.NamespacedReference `json:"policyIdRef,omitempty" tf:"-"`

	// Selector for a OrganizationPolicy in iam to populate policyId.
	// +kubebuilder:validation:Optional
	PolicyIDSelector *v2.NamespacedSelector `json:"policyIdSelector,omitempty" tf:"-"`

	// The ID of the user.
	// +crossplane:generate:reference:type=github.com/upbound/provider-vultr/apis/namespaced/iam/v1beta1.User
	// +kubebuilder:validation:Optional
	UserID *string `json:"userId,omitempty" tf:"user_id,omitempty"`

	// Reference to a User in iam to populate userId.
	// +kubebuilder:validation:Optional
	UserIDRef *v2.NamespacedReference `json:"userIdRef,omitempty" tf:"-"`

	// Selector for a User in iam to populate userId.
	// +kubebuilder:validation:Optional
	UserIDSelector *v2.NamespacedSelector `json:"userIdSelector,omitempty" tf:"-"`
}

// OrganizationPolicyUserAttachmentSpec defines the desired state of OrganizationPolicyUserAttachment
type OrganizationPolicyUserAttachmentSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            OrganizationPolicyUserAttachmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OrganizationPolicyUserAttachmentInitParameters `json:"initProvider,omitempty"`
}

// OrganizationPolicyUserAttachmentStatus defines the observed state of OrganizationPolicyUserAttachment.
type OrganizationPolicyUserAttachmentStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               OrganizationPolicyUserAttachmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// OrganizationPolicyUserAttachment is the Schema for the OrganizationPolicyUserAttachments API. Provides a Vultr organization policy user attachment resource. This can be used to attach an organization policy resource to a user resource on your Vultr account.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,vultr}
type OrganizationPolicyUserAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              OrganizationPolicyUserAttachmentSpec   `json:"spec"`
	Status            OrganizationPolicyUserAttachmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OrganizationPolicyUserAttachmentList contains a list of OrganizationPolicyUserAttachments
type OrganizationPolicyUserAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OrganizationPolicyUserAttachment `json:"items"`
}

// Repository type metadata.
var (
	OrganizationPolicyUserAttachment_Kind             = "OrganizationPolicyUserAttachment"
	OrganizationPolicyUserAttachment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OrganizationPolicyUserAttachment_Kind}.String()
	OrganizationPolicyUserAttachment_KindAPIVersion   = OrganizationPolicyUserAttachment_Kind + "." + CRDGroupVersion.String()
	OrganizationPolicyUserAttachment_GroupVersionKind = CRDGroupVersion.WithKind(OrganizationPolicyUserAttachment_Kind)
)

func init() {
	SchemeBuilder.Register(&OrganizationPolicyUserAttachment{}, &OrganizationPolicyUserAttachmentList{})
}
