// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type OrganizationRoleTrustInitParameters struct {

	// ISO 8601 date time stamp indicating when to expire the role trust.
	DateExpires *string `json:"dateExpires,omitempty" tf:"date_expires,omitempty"`

	// +crossplane:generate:reference:type=github.com/upbound/provider-vultr/apis/namespaced/iam/v1beta1.OrganizationGroup
	Group *string `json:"group,omitempty" tf:"group,omitempty"`

	// Reference to a OrganizationGroup in iam to populate group.
	// +kubebuilder:validation:Optional
	GroupRef *v2.NamespacedReference `json:"groupRef,omitempty" tf:"-"`

	// Selector for a OrganizationGroup in iam to populate group.
	// +kubebuilder:validation:Optional
	GroupSelector *v2.NamespacedSelector `json:"groupSelector,omitempty" tf:"-"`

	// The hour that the role trust ends.
	HourEnd *int64 `json:"hourEnd,omitempty" tf:"hour_end,omitempty"`

	// The hour that the role trust begins.
	HourStart *int64 `json:"hourStart,omitempty" tf:"hour_start,omitempty"`

	// A list of IP ranges allowed for the role trust.
	// +listType=set
	IPRange []*string `json:"ipRange,omitempty" tf:"ip_range,omitempty"`

	// +crossplane:generate:reference:type=github.com/upbound/provider-vultr/apis/namespaced/iam/v1beta1.OrganizationRole
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// Reference to a OrganizationRole in iam to populate role.
	// +kubebuilder:validation:Optional
	RoleRef *v2.NamespacedReference `json:"roleRef,omitempty" tf:"-"`

	// Selector for a OrganizationRole in iam to populate role.
	// +kubebuilder:validation:Optional
	RoleSelector *v2.NamespacedSelector `json:"roleSelector,omitempty" tf:"-"`

	// The type of role trust.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// +crossplane:generate:reference:type=github.com/upbound/provider-vultr/apis/namespaced/iam/v1beta1.User
	User *string `json:"user,omitempty" tf:"user,omitempty"`

	// Reference to a User in iam to populate user.
	// +kubebuilder:validation:Optional
	UserRef *v2.NamespacedReference `json:"userRef,omitempty" tf:"-"`

	// Selector for a User in iam to populate user.
	// +kubebuilder:validation:Optional
	UserSelector *v2.NamespacedSelector `json:"userSelector,omitempty" tf:"-"`
}

type OrganizationRoleTrustObservation struct {

	// The date the role trust was created.
	DateCreated *string `json:"dateCreated,omitempty" tf:"date_created,omitempty"`

	// ISO 8601 date time stamp indicating when to expire the role trust.
	DateExpires *string `json:"dateExpires,omitempty" tf:"date_expires,omitempty"`

	Group *string `json:"group,omitempty" tf:"group,omitempty"`

	// The hour that the role trust ends.
	HourEnd *int64 `json:"hourEnd,omitempty" tf:"hour_end,omitempty"`

	// The hour that the role trust begins.
	HourStart *int64 `json:"hourStart,omitempty" tf:"hour_start,omitempty"`

	// The ID of the role trust.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A list of IP ranges allowed for the role trust.
	// +listType=set
	IPRange []*string `json:"ipRange,omitempty" tf:"ip_range,omitempty"`

	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// The type of role trust.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	User *string `json:"user,omitempty" tf:"user,omitempty"`
}

type OrganizationRoleTrustParameters struct {

	// ISO 8601 date time stamp indicating when to expire the role trust.
	// +kubebuilder:validation:Optional
	DateExpires *string `json:"dateExpires,omitempty" tf:"date_expires,omitempty"`

	// +crossplane:generate:reference:type=github.com/upbound/provider-vultr/apis/namespaced/iam/v1beta1.OrganizationGroup
	// +kubebuilder:validation:Optional
	Group *string `json:"group,omitempty" tf:"group,omitempty"`

	// Reference to a OrganizationGroup in iam to populate group.
	// +kubebuilder:validation:Optional
	GroupRef *v2.NamespacedReference `json:"groupRef,omitempty" tf:"-"`

	// Selector for a OrganizationGroup in iam to populate group.
	// +kubebuilder:validation:Optional
	GroupSelector *v2.NamespacedSelector `json:"groupSelector,omitempty" tf:"-"`

	// The hour that the role trust ends.
	// +kubebuilder:validation:Optional
	HourEnd *int64 `json:"hourEnd,omitempty" tf:"hour_end,omitempty"`

	// The hour that the role trust begins.
	// +kubebuilder:validation:Optional
	HourStart *int64 `json:"hourStart,omitempty" tf:"hour_start,omitempty"`

	// A list of IP ranges allowed for the role trust.
	// +kubebuilder:validation:Optional
	// +listType=set
	IPRange []*string `json:"ipRange,omitempty" tf:"ip_range,omitempty"`

	// +crossplane:generate:reference:type=github.com/upbound/provider-vultr/apis/namespaced/iam/v1beta1.OrganizationRole
	// +kubebuilder:validation:Optional
	Role *string `json:"role,omitempty" tf:"role,omitempty"`

	// Reference to a OrganizationRole in iam to populate role.
	// +kubebuilder:validation:Optional
	RoleRef *v2.NamespacedReference `json:"roleRef,omitempty" tf:"-"`

	// Selector for a OrganizationRole in iam to populate role.
	// +kubebuilder:validation:Optional
	RoleSelector *v2.NamespacedSelector `json:"roleSelector,omitempty" tf:"-"`

	// The type of role trust.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`

	// +crossplane:generate:reference:type=github.com/upbound/provider-vultr/apis/namespaced/iam/v1beta1.User
	// +kubebuilder:validation:Optional
	User *string `json:"user,omitempty" tf:"user,omitempty"`

	// Reference to a User in iam to populate user.
	// +kubebuilder:validation:Optional
	UserRef *v2.NamespacedReference `json:"userRef,omitempty" tf:"-"`

	// Selector for a User in iam to populate user.
	// +kubebuilder:validation:Optional
	UserSelector *v2.NamespacedSelector `json:"userSelector,omitempty" tf:"-"`
}

// OrganizationRoleTrustSpec defines the desired state of OrganizationRoleTrust
type OrganizationRoleTrustSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            OrganizationRoleTrustParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OrganizationRoleTrustInitParameters `json:"initProvider,omitempty"`
}

// OrganizationRoleTrustStatus defines the observed state of OrganizationRoleTrust.
type OrganizationRoleTrustStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               OrganizationRoleTrustObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// OrganizationRoleTrust is the Schema for the OrganizationRoleTrusts API. Provides a Vultr organization role trust resource. This can be used to create, read, update and delete an organization role trust resource on your Vultr account.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,vultr}
type OrganizationRoleTrust struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.type) || (has(self.initProvider) && has(self.initProvider.type))",message="spec.forProvider.type is a required parameter"
	Spec   OrganizationRoleTrustSpec   `json:"spec"`
	Status OrganizationRoleTrustStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OrganizationRoleTrustList contains a list of OrganizationRoleTrusts
type OrganizationRoleTrustList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OrganizationRoleTrust `json:"items"`
}

// Repository type metadata.
var (
	OrganizationRoleTrust_Kind             = "OrganizationRoleTrust"
	OrganizationRoleTrust_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OrganizationRoleTrust_Kind}.String()
	OrganizationRoleTrust_KindAPIVersion   = OrganizationRoleTrust_Kind + "." + CRDGroupVersion.String()
	OrganizationRoleTrust_GroupVersionKind = CRDGroupVersion.WithKind(OrganizationRoleTrust_Kind)
)

func init() {
	SchemeBuilder.Register(&OrganizationRoleTrust{}, &OrganizationRoleTrustList{})
}
