// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

// Hub marks this type as a conversion hub.
func (tr *DNSDomain) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *DNSRecord) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *FirewallGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *FirewallRule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *LoadBalancer) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NATGateway) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NATGatewayFirewallRule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *NATGatewayPortForwardingRule) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ReservedIP) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ReverseIPv4) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ReverseIPv6) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VPC) Hub() {}
