// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ReverseIPv4InitParameters struct {

	// The IPv4 address used in the reverse DNS record.
	// +crossplane:generate:reference:type=github.com/upbound/provider-vultr/apis/namespaced/compute/v1beta1.Instance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("main_ip",true)
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// Reference to a Instance in compute to populate ip.
	// +kubebuilder:validation:Optional
	IPRef *v2.NamespacedReference `json:"ipRef,omitempty" tf:"-"`

	// Selector for a Instance in compute to populate ip.
	// +kubebuilder:validation:Optional
	IPSelector *v2.NamespacedSelector `json:"ipSelector,omitempty" tf:"-"`

	// The ID of the instance you want to set an IPv4
	// reverse DNS record for.
	// +crossplane:generate:reference:type=github.com/upbound/provider-vultr/apis/namespaced/compute/v1beta1.Instance
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a Instance in compute to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v2.NamespacedReference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in compute to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v2.NamespacedSelector `json:"instanceIdSelector,omitempty" tf:"-"`

	// The hostname used in the IPv4 reverse DNS record.
	Reverse *string `json:"reverse,omitempty" tf:"reverse,omitempty"`
}

type ReverseIPv4Observation struct {

	// The gateway IP address.
	Gateway *string `json:"gateway,omitempty" tf:"gateway,omitempty"`

	// The ID is the IPv4 address in canonical format.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The IPv4 address used in the reverse DNS record.
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// The ID of the instance you want to set an IPv4
	// reverse DNS record for.
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// The IPv4 netmask in dot-decimal notation.
	Netmask *string `json:"netmask,omitempty" tf:"netmask,omitempty"`

	// The hostname used in the IPv4 reverse DNS record.
	Reverse *string `json:"reverse,omitempty" tf:"reverse,omitempty"`
}

type ReverseIPv4Parameters struct {

	// The IPv4 address used in the reverse DNS record.
	// +crossplane:generate:reference:type=github.com/upbound/provider-vultr/apis/namespaced/compute/v1beta1.Instance
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractParamPath("main_ip",true)
	// +kubebuilder:validation:Optional
	IP *string `json:"ip,omitempty" tf:"ip,omitempty"`

	// Reference to a Instance in compute to populate ip.
	// +kubebuilder:validation:Optional
	IPRef *v2.NamespacedReference `json:"ipRef,omitempty" tf:"-"`

	// Selector for a Instance in compute to populate ip.
	// +kubebuilder:validation:Optional
	IPSelector *v2.NamespacedSelector `json:"ipSelector,omitempty" tf:"-"`

	// The ID of the instance you want to set an IPv4
	// reverse DNS record for.
	// +crossplane:generate:reference:type=github.com/upbound/provider-vultr/apis/namespaced/compute/v1beta1.Instance
	// +kubebuilder:validation:Optional
	InstanceID *string `json:"instanceId,omitempty" tf:"instance_id,omitempty"`

	// Reference to a Instance in compute to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDRef *v2.NamespacedReference `json:"instanceIdRef,omitempty" tf:"-"`

	// Selector for a Instance in compute to populate instanceId.
	// +kubebuilder:validation:Optional
	InstanceIDSelector *v2.NamespacedSelector `json:"instanceIdSelector,omitempty" tf:"-"`

	// The hostname used in the IPv4 reverse DNS record.
	// +kubebuilder:validation:Optional
	Reverse *string `json:"reverse,omitempty" tf:"reverse,omitempty"`
}

// ReverseIPv4Spec defines the desired state of ReverseIPv4
type ReverseIPv4Spec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ReverseIPv4Parameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ReverseIPv4InitParameters `json:"initProvider,omitempty"`
}

// ReverseIPv4Status defines the observed state of ReverseIPv4.
type ReverseIPv4Status struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ReverseIPv4Observation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ReverseIPv4 is the Schema for the ReverseIPv4s API. Provides a Vultr Reverse IPv4 resource. This can be used to create, read, and modify reverse DNS records for IPv4 addresses.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,vultr}
type ReverseIPv4 struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.reverse) || (has(self.initProvider) && has(self.initProvider.reverse))",message="spec.forProvider.reverse is a required parameter"
	Spec   ReverseIPv4Spec   `json:"spec"`
	Status ReverseIPv4Status `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ReverseIPv4List contains a list of ReverseIPv4s
type ReverseIPv4List struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ReverseIPv4 `json:"items"`
}

// Repository type metadata.
var (
	ReverseIPv4_Kind             = "ReverseIPv4"
	ReverseIPv4_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ReverseIPv4_Kind}.String()
	ReverseIPv4_KindAPIVersion   = ReverseIPv4_Kind + "." + CRDGroupVersion.String()
	ReverseIPv4_GroupVersionKind = CRDGroupVersion.WithKind(ReverseIPv4_Kind)
)

func init() {
	SchemeBuilder.Register(&ReverseIPv4{}, &ReverseIPv4List{})
}
