// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type VPCInitParameters struct {

	// The description you want to give your VPC.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The region ID that you want the VPC to be created in.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The IPv4 subnet to be used when attaching instances to this VPC.
	V4Subnet *string `json:"v4Subnet,omitempty" tf:"v4_subnet,omitempty"`

	// The number of bits for the netmask in CIDR notation. Example: 32
	V4SubnetMask *int64 `json:"v4SubnetMask,omitempty" tf:"v4_subnet_mask,omitempty"`
}

type VPCObservation struct {

	// The date that the VPC was added to your Vultr account.
	DateCreated *string `json:"dateCreated,omitempty" tf:"date_created,omitempty"`

	// The description you want to give your VPC.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// ID of the VPC.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The region ID that you want the VPC to be created in.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The IPv4 subnet to be used when attaching instances to this VPC.
	V4Subnet *string `json:"v4Subnet,omitempty" tf:"v4_subnet,omitempty"`

	// The number of bits for the netmask in CIDR notation. Example: 32
	V4SubnetMask *int64 `json:"v4SubnetMask,omitempty" tf:"v4_subnet_mask,omitempty"`
}

type VPCParameters struct {

	// The description you want to give your VPC.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The region ID that you want the VPC to be created in.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The IPv4 subnet to be used when attaching instances to this VPC.
	// +kubebuilder:validation:Optional
	V4Subnet *string `json:"v4Subnet,omitempty" tf:"v4_subnet,omitempty"`

	// The number of bits for the netmask in CIDR notation. Example: 32
	// +kubebuilder:validation:Optional
	V4SubnetMask *int64 `json:"v4SubnetMask,omitempty" tf:"v4_subnet_mask,omitempty"`
}

// VPCSpec defines the desired state of VPC
type VPCSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            VPCParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider VPCInitParameters `json:"initProvider,omitempty"`
}

// VPCStatus defines the observed state of VPC.
type VPCStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               VPCObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// VPC is the Schema for the VPCs API. Provides a Vultr VPC resource. This can be used to create, read, and delete VPCs on your Vultr account.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,vultr}
type VPC struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.region) || (has(self.initProvider) && has(self.initProvider.region))",message="spec.forProvider.region is a required parameter"
	Spec   VPCSpec   `json:"spec"`
	Status VPCStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// VPCList contains a list of VPCs
type VPCList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []VPC `json:"items"`
}

// Repository type metadata.
var (
	VPC_Kind             = "VPC"
	VPC_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: VPC_Kind}.String()
	VPC_KindAPIVersion   = VPC_Kind + "." + CRDGroupVersion.String()
	VPC_GroupVersionKind = CRDGroupVersion.WithKind(VPC_Kind)
)

func init() {
	SchemeBuilder.Register(&VPC{}, &VPCList{})
}
