// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

// Hub marks this type as a conversion hub.
func (tr *OIDCIssuer) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OIDCProvider) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OIDCToken) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *Organization) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OrganizationGroup) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OrganizationInvitation) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OrganizationPolicy) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OrganizationPolicyGroupAttachment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OrganizationPolicyUserAttachment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OrganizationRole) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OrganizationRoleGroupAttachment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OrganizationRolePolicyAttachment) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OrganizationRoleSession) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *OrganizationRoleTrust) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *User) Hub() {}
