// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type OrganizationGroupInitParameters struct {

	// A description of the organization group.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The name of the organization group.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type OrganizationGroupObservation struct {

	// Date of creation for the organization group.
	DateCreated *string `json:"dateCreated,omitempty" tf:"date_created,omitempty"`

	// A description of the organization group.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The ID of the organization group.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name of the organization group.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// NOTE This field is temporarily ignored until the API is fixed. A list of policies attached to the organization group.
	// +listType=set
	Policies []*string `json:"policies,omitempty" tf:"policies,omitempty"`

	// A list of roles attached to the organization group.
	// +listType=set
	Roles []*string `json:"roles,omitempty" tf:"roles,omitempty"`

	// A list of users attached to the organization group.
	// +listType=set
	Users []*string `json:"users,omitempty" tf:"users,omitempty"`
}

type OrganizationGroupParameters struct {

	// A description of the organization group.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// The name of the organization group.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

// OrganizationGroupSpec defines the desired state of OrganizationGroup
type OrganizationGroupSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   OrganizationGroupParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OrganizationGroupInitParameters `json:"initProvider,omitempty"`
}

// OrganizationGroupStatus defines the observed state of OrganizationGroup.
type OrganizationGroupStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               OrganizationGroupObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// OrganizationGroup is the Schema for the OrganizationGroups API. Provides a Vultr organization group resource. This can be used to create, read, update and delete an organization group resource on your Vultr account.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vultr}
type OrganizationGroup struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.description) || (has(self.initProvider) && has(self.initProvider.description))",message="spec.forProvider.description is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   OrganizationGroupSpec   `json:"spec"`
	Status OrganizationGroupStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OrganizationGroupList contains a list of OrganizationGroups
type OrganizationGroupList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OrganizationGroup `json:"items"`
}

// Repository type metadata.
var (
	OrganizationGroup_Kind             = "OrganizationGroup"
	OrganizationGroup_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OrganizationGroup_Kind}.String()
	OrganizationGroup_KindAPIVersion   = OrganizationGroup_Kind + "." + CRDGroupVersion.String()
	OrganizationGroup_GroupVersionKind = CRDGroupVersion.WithKind(OrganizationGroup_Kind)
)

func init() {
	SchemeBuilder.Register(&OrganizationGroup{}, &OrganizationGroupList{})
}
