// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type DocumentInitParameters struct {

	// A list of blocks for the organization policy statements.
	Statement []StatementInitParameters `json:"statement,omitempty" tf:"statement,omitempty"`

	// A version for organization policy document.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type DocumentObservation struct {

	// A list of blocks for the organization policy statements.
	Statement []StatementObservation `json:"statement,omitempty" tf:"statement,omitempty"`

	// A version for organization policy document.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type DocumentParameters struct {

	// A list of blocks for the organization policy statements.
	// +kubebuilder:validation:Optional
	Statement []StatementParameters `json:"statement" tf:"statement,omitempty"`

	// A version for organization policy document.
	// +kubebuilder:validation:Optional
	Version *string `json:"version" tf:"version,omitempty"`
}

type OrganizationPolicyInitParameters struct {

	// A description of the organization policy.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A block outlining the organization policy document details.
	Document *DocumentInitParameters `json:"document,omitempty" tf:"document,omitempty"`

	// The name of the organization policy.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type OrganizationPolicyObservation struct {
	DateCreated *string `json:"dateCreated,omitempty" tf:"date_created,omitempty"`

	// A description of the organization policy.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A block outlining the organization policy document details.
	Document *DocumentObservation `json:"document,omitempty" tf:"document,omitempty"`

	// The ID of the organization policy.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Whether or not the policy is a system policy.
	IsSystemPolicy *bool `json:"isSystemPolicy,omitempty" tf:"is_system_policy,omitempty"`

	// The name of the organization policy.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type OrganizationPolicyParameters struct {

	// A description of the organization policy.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// A block outlining the organization policy document details.
	// +kubebuilder:validation:Optional
	Document *DocumentParameters `json:"document,omitempty" tf:"document,omitempty"`

	// The name of the organization policy.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`
}

type StatementInitParameters struct {

	// A list of actions for the policy document statement.
	Actions []*string `json:"actions,omitempty" tf:"actions,omitempty"`

	// The effect of the the policy document statement.
	Effect *string `json:"effect,omitempty" tf:"effect,omitempty"`

	// A list of applicable resources for the policy document statement.
	Resources []*string `json:"resources,omitempty" tf:"resources,omitempty"`
}

type StatementObservation struct {

	// A list of actions for the policy document statement.
	Actions []*string `json:"actions,omitempty" tf:"actions,omitempty"`

	// The effect of the the policy document statement.
	Effect *string `json:"effect,omitempty" tf:"effect,omitempty"`

	// A list of applicable resources for the policy document statement.
	Resources []*string `json:"resources,omitempty" tf:"resources,omitempty"`
}

type StatementParameters struct {

	// A list of actions for the policy document statement.
	// +kubebuilder:validation:Optional
	Actions []*string `json:"actions" tf:"actions,omitempty"`

	// The effect of the the policy document statement.
	// +kubebuilder:validation:Optional
	Effect *string `json:"effect" tf:"effect,omitempty"`

	// A list of applicable resources for the policy document statement.
	// +kubebuilder:validation:Optional
	Resources []*string `json:"resources" tf:"resources,omitempty"`
}

// OrganizationPolicySpec defines the desired state of OrganizationPolicy
type OrganizationPolicySpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   OrganizationPolicyParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OrganizationPolicyInitParameters `json:"initProvider,omitempty"`
}

// OrganizationPolicyStatus defines the observed state of OrganizationPolicy.
type OrganizationPolicyStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               OrganizationPolicyObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// OrganizationPolicy is the Schema for the OrganizationPolicys API. Provides a Vultr organization policy resource. This can be used to create, read, update and delete an organization policy resource on your Vultr account.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vultr}
type OrganizationPolicy struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.description) || (has(self.initProvider) && has(self.initProvider.description))",message="spec.forProvider.description is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.document) || (has(self.initProvider) && has(self.initProvider.document))",message="spec.forProvider.document is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	Spec   OrganizationPolicySpec   `json:"spec"`
	Status OrganizationPolicyStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OrganizationPolicyList contains a list of OrganizationPolicys
type OrganizationPolicyList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OrganizationPolicy `json:"items"`
}

// Repository type metadata.
var (
	OrganizationPolicy_Kind             = "OrganizationPolicy"
	OrganizationPolicy_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OrganizationPolicy_Kind}.String()
	OrganizationPolicy_KindAPIVersion   = OrganizationPolicy_Kind + "." + CRDGroupVersion.String()
	OrganizationPolicy_GroupVersionKind = CRDGroupVersion.WithKind(OrganizationPolicy_Kind)
)

func init() {
	SchemeBuilder.Register(&OrganizationPolicy{}, &OrganizationPolicyList{})
}
