// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type OrganizationPolicyGroupAttachmentInitParameters struct {

	// The ID of the group.
	// +crossplane:generate:reference:type=github.com/upbound/provider-vultr/apis/cluster/iam/v1beta1.OrganizationGroup
	GroupID *string `json:"groupId,omitempty" tf:"group_id,omitempty"`

	// Reference to a OrganizationGroup in iam to populate groupId.
	// +kubebuilder:validation:Optional
	GroupIDRef *v2.Reference `json:"groupIdRef,omitempty" tf:"-"`

	// Selector for a OrganizationGroup in iam to populate groupId.
	// +kubebuilder:validation:Optional
	GroupIDSelector *v2.Selector `json:"groupIdSelector,omitempty" tf:"-"`

	// The ID of the policy.
	// +crossplane:generate:reference:type=github.com/upbound/provider-vultr/apis/cluster/iam/v1beta1.OrganizationPolicy
	PolicyID *string `json:"policyId,omitempty" tf:"policy_id,omitempty"`

	// Reference to a OrganizationPolicy in iam to populate policyId.
	// +kubebuilder:validation:Optional
	PolicyIDRef *v2.Reference `json:"policyIdRef,omitempty" tf:"-"`

	// Selector for a OrganizationPolicy in iam to populate policyId.
	// +kubebuilder:validation:Optional
	PolicyIDSelector *v2.Selector `json:"policyIdSelector,omitempty" tf:"-"`
}

type OrganizationPolicyGroupAttachmentObservation struct {

	// The ID of the group.
	GroupID *string `json:"groupId,omitempty" tf:"group_id,omitempty"`

	// The ID of the policy group attachment (a composite of the policy_id and group_id).
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The ID of the policy.
	PolicyID *string `json:"policyId,omitempty" tf:"policy_id,omitempty"`
}

type OrganizationPolicyGroupAttachmentParameters struct {

	// The ID of the group.
	// +crossplane:generate:reference:type=github.com/upbound/provider-vultr/apis/cluster/iam/v1beta1.OrganizationGroup
	// +kubebuilder:validation:Optional
	GroupID *string `json:"groupId,omitempty" tf:"group_id,omitempty"`

	// Reference to a OrganizationGroup in iam to populate groupId.
	// +kubebuilder:validation:Optional
	GroupIDRef *v2.Reference `json:"groupIdRef,omitempty" tf:"-"`

	// Selector for a OrganizationGroup in iam to populate groupId.
	// +kubebuilder:validation:Optional
	GroupIDSelector *v2.Selector `json:"groupIdSelector,omitempty" tf:"-"`

	// The ID of the policy.
	// +crossplane:generate:reference:type=github.com/upbound/provider-vultr/apis/cluster/iam/v1beta1.OrganizationPolicy
	// +kubebuilder:validation:Optional
	PolicyID *string `json:"policyId,omitempty" tf:"policy_id,omitempty"`

	// Reference to a OrganizationPolicy in iam to populate policyId.
	// +kubebuilder:validation:Optional
	PolicyIDRef *v2.Reference `json:"policyIdRef,omitempty" tf:"-"`

	// Selector for a OrganizationPolicy in iam to populate policyId.
	// +kubebuilder:validation:Optional
	PolicyIDSelector *v2.Selector `json:"policyIdSelector,omitempty" tf:"-"`
}

// OrganizationPolicyGroupAttachmentSpec defines the desired state of OrganizationPolicyGroupAttachment
type OrganizationPolicyGroupAttachmentSpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   OrganizationPolicyGroupAttachmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider OrganizationPolicyGroupAttachmentInitParameters `json:"initProvider,omitempty"`
}

// OrganizationPolicyGroupAttachmentStatus defines the observed state of OrganizationPolicyGroupAttachment.
type OrganizationPolicyGroupAttachmentStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               OrganizationPolicyGroupAttachmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// OrganizationPolicyGroupAttachment is the Schema for the OrganizationPolicyGroupAttachments API. Provides a Vultr organization policy group attachment resource. This can be used to attach an organization policy resource to a group resource on your Vultr account.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vultr}
type OrganizationPolicyGroupAttachment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              OrganizationPolicyGroupAttachmentSpec   `json:"spec"`
	Status            OrganizationPolicyGroupAttachmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// OrganizationPolicyGroupAttachmentList contains a list of OrganizationPolicyGroupAttachments
type OrganizationPolicyGroupAttachmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []OrganizationPolicyGroupAttachment `json:"items"`
}

// Repository type metadata.
var (
	OrganizationPolicyGroupAttachment_Kind             = "OrganizationPolicyGroupAttachment"
	OrganizationPolicyGroupAttachment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: OrganizationPolicyGroupAttachment_Kind}.String()
	OrganizationPolicyGroupAttachment_KindAPIVersion   = OrganizationPolicyGroupAttachment_Kind + "." + CRDGroupVersion.String()
	OrganizationPolicyGroupAttachment_GroupVersionKind = CRDGroupVersion.WithKind(OrganizationPolicyGroupAttachment_Kind)
)

func init() {
	SchemeBuilder.Register(&OrganizationPolicyGroupAttachment{}, &OrganizationPolicyGroupAttachmentList{})
}
