apiVersion: compute.vultr.upbound.io/v1beta1
kind: Inference
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/inference
  labels:
    testing.upbound.io/example-name: example-inference
  name: example-inference
spec:
  forProvider:
    label: example-inference
  writeConnectionSecretToRef:
    name: example-inference-conn
    namespace: upbound-system
