// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

// Hub marks this type as a conversion hub.
func (tr *BlockStorage) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ContainerRegistry) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ObjectStorage) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *ObjectStorageBucket) Hub() {}

// Hub marks this type as a conversion hub.
func (tr *VirtualFileSystemStorage) Hub() {}
