// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0
// Code transformed by upjet. DO NOT EDIT.

// Code generated by angryjet. DO NOT EDIT.

package v1beta1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	xpresource "github.com/crossplane/crossplane-runtime/v2/pkg/resource"
	errors "github.com/pkg/errors"
	apisresolver "github.com/upbound/provider-vultr/internal/apis"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

func (mg *ObjectStorageBucket) ResolveReferences( // ResolveReferences of this ObjectStorageBucket.
	ctx context.Context, c client.Reader) error {
	var m xpresource.Managed
	var l xpresource.ManagedList
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error
	{
		m, l, err = apisresolver.GetManagedResource("storage.vultr.m.upbound.io", "v1beta1", "ObjectStorage", "ObjectStorageList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ObjectStorageID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.ObjectStorageIDRef,
			Selector:     mg.Spec.ForProvider.ObjectStorageIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ObjectStorageID")
	}
	mg.Spec.ForProvider.ObjectStorageID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ObjectStorageIDRef = rsp.ResolvedReference
	{
		m, l, err = apisresolver.GetManagedResource("storage.vultr.m.upbound.io", "v1beta1", "ObjectStorage", "ObjectStorageList")
		if err != nil {
			return errors.Wrap(err, "failed to get the reference target managed resource and its list for reference resolution")
		}

		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ObjectStorageID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.ObjectStorageIDRef,
			Selector:     mg.Spec.InitProvider.ObjectStorageIDSelector,
			To:           reference.To{List: l, Managed: m},
		})
	}
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ObjectStorageID")
	}
	mg.Spec.InitProvider.ObjectStorageID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ObjectStorageIDRef = rsp.ResolvedReference

	return nil
}
