apiVersion: database.vultr.m.upbound.io/v1beta1
kind: Topic
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1beta1/topic
  labels:
    testing.upbound.io/example-name: my_database_topic
  name: my-database-topic
  namespace: upbound-system
spec:
  forProvider:
    databaseIdSelector:
      matchLabels:
        testing.upbound.io/example-name: my_database
    name: my_database_topic
    partitions: "3"
    replication: "2"
    retentionBytes: "-1"
    retentionHours: "120"
