// SPDX-FileCopyrightText: 2026 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1beta1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v2 "github.com/crossplane/crossplane/apis/v2/core/v2"
)

type ContainerRegistryInitParameters struct {

	// The name for your container registry.  Must be lowercase and only alphanumeric characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The billing plan for the container registry. See available plans
	Plan *string `json:"plan,omitempty" tf:"plan,omitempty"`

	// Boolean indicating if the container registry should be created with public visibility or if it should require credentials.
	Public *bool `json:"public,omitempty" tf:"public,omitempty"`

	// The region where your container registry will be deployed. See available regions
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type ContainerRegistryObservation struct {

	// A date-time denoting when the container registry was created.
	DateCreated *string `json:"dateCreated,omitempty" tf:"date_created,omitempty"`

	// The container registry ID.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The name for your container registry.  Must be lowercase and only alphanumeric characters.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The billing plan for the container registry. See available plans
	Plan *string `json:"plan,omitempty" tf:"plan,omitempty"`

	// Boolean indicating if the container registry should be created with public visibility or if it should require credentials.
	Public *bool `json:"public,omitempty" tf:"public,omitempty"`

	// The region where your container registry will be deployed. See available regions
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// The user associated with the container registry.
	RootUser map[string]string `json:"rootUser,omitempty" tf:"root_user,omitempty"`

	// A listing of current storage usage relevant to the container registry.
	Storage map[string]string `json:"storage,omitempty" tf:"storage,omitempty"`

	// The URN of the container registry.
	Urn *string `json:"urn,omitempty" tf:"urn,omitempty"`
}

type ContainerRegistryParameters struct {

	// The name for your container registry.  Must be lowercase and only alphanumeric characters.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The billing plan for the container registry. See available plans
	// +kubebuilder:validation:Optional
	Plan *string `json:"plan,omitempty" tf:"plan,omitempty"`

	// Boolean indicating if the container registry should be created with public visibility or if it should require credentials.
	// +kubebuilder:validation:Optional
	Public *bool `json:"public,omitempty" tf:"public,omitempty"`

	// The region where your container registry will be deployed. See available regions
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

// ContainerRegistrySpec defines the desired state of ContainerRegistry
type ContainerRegistrySpec struct {
	v2.ClusterManagedResourceSpec `json:",inline"`
	ForProvider                   ContainerRegistryParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ContainerRegistryInitParameters `json:"initProvider,omitempty"`
}

// ContainerRegistryStatus defines the observed state of ContainerRegistry.
type ContainerRegistryStatus struct {
	v2.ManagedResourceStatus `json:",inline"`
	AtProvider               ContainerRegistryObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ContainerRegistry is the Schema for the ContainerRegistrys API. Provides a Vultr container registry resource. This can be used to create, read, modify, and delete registries on your Vultr account.
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,vultr}
type ContainerRegistry struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.plan) || (has(self.initProvider) && has(self.initProvider.plan))",message="spec.forProvider.plan is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.public) || (has(self.initProvider) && has(self.initProvider.public))",message="spec.forProvider.public is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.region) || (has(self.initProvider) && has(self.initProvider.region))",message="spec.forProvider.region is a required parameter"
	Spec   ContainerRegistrySpec   `json:"spec"`
	Status ContainerRegistryStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ContainerRegistryList contains a list of ContainerRegistrys
type ContainerRegistryList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ContainerRegistry `json:"items"`
}

// Repository type metadata.
var (
	ContainerRegistry_Kind             = "ContainerRegistry"
	ContainerRegistry_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ContainerRegistry_Kind}.String()
	ContainerRegistry_KindAPIVersion   = ContainerRegistry_Kind + "." + CRDGroupVersion.String()
	ContainerRegistry_GroupVersionKind = CRDGroupVersion.WithKind(ContainerRegistry_Kind)
)

func init() {
	SchemeBuilder.Register(&ContainerRegistry{}, &ContainerRegistryList{})
}
