apiVersion: compute.vultr.m.upbound.io/v1beta1
kind: BareMetalServer
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/baremetalserver
  labels:
    testing.upbound.io/example-name: my_server
  name: my-server
  namespace: upbound-system
spec:
  forProvider:
    osId: 1743
    plan: vbm-4c-32gb
    region: ewr
