apiVersion: iam.vultr.m.upbound.io/v1beta1
kind: OrganizationPolicy
metadata:
  annotations:
    meta.upbound.io/example-id: iam/v1beta1/organizationpolicy
  labels:
    testing.upbound.io/example-name: example-organizationpolicy
  name: example-organizationpolicy
  namespace: upbound-system
spec:
  forProvider:
    name: uptest-policy
    description: example organization policy
    document:
      version: "2012-10-17"
      statement:
        - actions:
            - network.dns.*
          effect: Allow
          resources:
            - "*"
