apiVersion: storage.vultr.m.upbound.io/v1beta1
kind: ObjectStorageBucket
metadata:
  annotations:
    meta.upbound.io/example-id: storage/v1beta1/objectstoragebucket
  labels:
    testing.upbound.io/example-name: obj-bucket
  name: obj-bucket
  namespace: upbound-system
spec:
  forProvider:
    enableLock: true
    enableVersioning: true
    name: my-bucket
    objectStorageIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
