apiVersion: compute.vultr.upbound.io/v1beta1
kind: Snapshot
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/snapshot
  labels:
    testing.upbound.io/example-name: my_snapshot
  name: my-snapshot
spec:
  forProvider:
    description: my instances snapshot
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: my_instance

---

apiVersion: compute.vultr.upbound.io/v1beta1
kind: Instance
metadata:
  annotations:
    meta.upbound.io/example-id: compute/v1beta1/snapshot
  labels:
    testing.upbound.io/example-name: my_instance
  name: my-instance
spec:
  forProvider:
    label: my_instance
    osId: 167
    plan: 201
    region: ewr
