apiVersion: database.vultr.upbound.io/v1beta1
kind: Quota
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1beta1/quota
  labels:
    testing.upbound.io/example-name: my_database_quota
  name: my-database-quota
spec:
  forProvider:
    clientId: my_database_quota
    consumerByteRate: "3"
    databaseIdSelector:
      matchLabels:
        testing.upbound.io/example-name: my_database
    producerByteRate: "2"
    requestPercentage: "120"
    userSelector:
      matchLabels:
        testing.upbound.io/example-name: example
