apiVersion: meta.pkg.crossplane.io/v1
kind: Provider
metadata:
  name: provider-vultr
  annotations:
    meta.crossplane.io/maintainer: Upbound <support@upbound.io>
    meta.crossplane.io/source: github.com/upbound/provider-upjet-vultr
    meta.crossplane.io/license: Apache-2.0
    meta.crossplane.io/description: |
      Upbound's Crossplane provider to manage Vultr services in Kubernetes.
    meta.crossplane.io/readme: |
      Provider Vultr is a Crossplane provider for [Vultr](https://www.vultr.com/)
      developed by Upbound.
      Available resources and their fields can be found in the [Upbound
      Marketplace](https://marketplace.upbound.io/providers/upbound/provider-vultr).
spec:
  crossplane:
    version: ">=v1.14.0-0"
  capabilities:
  - SafeStart
